// <auto-generated>
/*
 * Deadlock API
 *
 *  ## API Clients  We have auto generated and updated clients for many languages. You can find them here: [https://github.com/deadlock-api/openapi-clients](https://github.com/deadlock-api/openapi-clients)  ## Support the Deadlock API  Whether you're building your own database, developing data science projects, or enhancing your website with game and player analytics, the Deadlock API has the data you need.  Your sponsorship helps keep this resource open, free and future-proof for everyone. By supporting the Deadlock API, you will enable continued development, new features and reliable access for developers, analysts and streamers worldwide.  Help us continue to provide the data you need - sponsor the Deadlock API today!  **-> You can Sponsor the Deadlock API on [Patreon](https://www.patreon.com/c/user?u=68961896) or [GitHub](https://github.com/sponsors/raimannma)**  ## Disclaimer _deadlock-api.com is not endorsed by Valve and does not reflect the views or opinions of Valve or anyone officially involved in producing or managing Valve properties. Valve and all associated properties are trademarks or registered trademarks of Valve Corporation_         
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using DeadlockApiClient.Client;

namespace DeadlockApiClient.Model
{
    /// <summary>
    /// Ability
    /// </summary>
    public partial class Ability : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Ability" /> class.
        /// </summary>
        /// <param name="className">className</param>
        /// <param name="description">description</param>
        /// <param name="id">id</param>
        /// <param name="name">name</param>
        /// <param name="type">type</param>
        /// <param name="abilityType">abilityType</param>
        /// <param name="behaviours">behaviours</param>
        /// <param name="bossDamageScale">bossDamageScale</param>
        /// <param name="dependantAbilities">dependantAbilities</param>
        /// <param name="dependentAbilities">dependentAbilities</param>
        /// <param name="grantAmmoOnCast">grantAmmoOnCast</param>
        /// <param name="hero">hero</param>
        /// <param name="heroes">heroes</param>
        /// <param name="image">image</param>
        /// <param name="imageWebp">imageWebp</param>
        /// <param name="properties">properties</param>
        /// <param name="startTrained">startTrained</param>
        /// <param name="tooltipDetails">tooltipDetails</param>
        /// <param name="updateTime">updateTime</param>
        /// <param name="upgrades">upgrades</param>
        /// <param name="videos">videos</param>
        /// <param name="weaponInfo">weaponInfo</param>
        [JsonConstructor]
        public Ability(string className, AbilityDescription description, int id, string name, ItemType type, Option<AbilityType?> abilityType = default, Option<List<string>?> behaviours = default, Option<double?> bossDamageScale = default, Option<List<string>?> dependantAbilities = default, Option<Dictionary<string, DependantAbilities>?> dependentAbilities = default, Option<bool?> grantAmmoOnCast = default, Option<int?> hero = default, Option<List<int>?> heroes = default, Option<string?> image = default, Option<string?> imageWebp = default, Option<Dictionary<string, ItemProperty>?> properties = default, Option<bool?> startTrained = default, Option<AbilityTooltipDetails?> tooltipDetails = default, Option<long?> updateTime = default, Option<List<RawAbilityUpgrade>?> upgrades = default, Option<AbilityVideos?> videos = default, Option<RawItemWeaponInfoInner?> weaponInfo = default)
        {
            ClassName = className;
            Description = description;
            Id = id;
            Name = name;
            Type = type;
            AbilityTypeOption = abilityType;
            BehavioursOption = behaviours;
            BossDamageScaleOption = bossDamageScale;
            DependantAbilitiesOption = dependantAbilities;
            DependentAbilitiesOption = dependentAbilities;
            GrantAmmoOnCastOption = grantAmmoOnCast;
            HeroOption = hero;
            HeroesOption = heroes;
            ImageOption = image;
            ImageWebpOption = imageWebp;
            PropertiesOption = properties;
            StartTrainedOption = startTrained;
            TooltipDetailsOption = tooltipDetails;
            UpdateTimeOption = updateTime;
            UpgradesOption = upgrades;
            VideosOption = videos;
            WeaponInfoOption = weaponInfo;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [JsonPropertyName("type")]
        public ItemType Type { get; set; }

        /// <summary>
        /// Used to track the state of AbilityType
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<AbilityType?> AbilityTypeOption { get; private set; }

        /// <summary>
        /// Gets or Sets AbilityType
        /// </summary>
        [JsonPropertyName("ability_type")]
        public AbilityType? AbilityType { get { return this.AbilityTypeOption.Value; } set { this.AbilityTypeOption = new(value); } }

        /// <summary>
        /// Gets or Sets ClassName
        /// </summary>
        [JsonPropertyName("class_name")]
        public string ClassName { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [JsonPropertyName("description")]
        public AbilityDescription Description { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public int Id { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>
        /// Used to track the state of Behaviours
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<string>?> BehavioursOption { get; private set; }

        /// <summary>
        /// Gets or Sets Behaviours
        /// </summary>
        [JsonPropertyName("behaviours")]
        public List<string>? Behaviours { get { return this.BehavioursOption.Value; } set { this.BehavioursOption = new(value); } }

        /// <summary>
        /// Used to track the state of BossDamageScale
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<double?> BossDamageScaleOption { get; private set; }

        /// <summary>
        /// Gets or Sets BossDamageScale
        /// </summary>
        [JsonPropertyName("boss_damage_scale")]
        public double? BossDamageScale { get { return this.BossDamageScaleOption.Value; } set { this.BossDamageScaleOption = new(value); } }

        /// <summary>
        /// Used to track the state of DependantAbilities
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<string>?> DependantAbilitiesOption { get; private set; }

        /// <summary>
        /// Gets or Sets DependantAbilities
        /// </summary>
        [JsonPropertyName("dependant_abilities")]
        public List<string>? DependantAbilities { get { return this.DependantAbilitiesOption.Value; } set { this.DependantAbilitiesOption = new(value); } }

        /// <summary>
        /// Used to track the state of DependentAbilities
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Dictionary<string, DependantAbilities>?> DependentAbilitiesOption { get; private set; }

        /// <summary>
        /// Gets or Sets DependentAbilities
        /// </summary>
        [JsonPropertyName("dependent_abilities")]
        public Dictionary<string, DependantAbilities>? DependentAbilities { get { return this.DependentAbilitiesOption.Value; } set { this.DependentAbilitiesOption = new(value); } }

        /// <summary>
        /// Used to track the state of GrantAmmoOnCast
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> GrantAmmoOnCastOption { get; private set; }

        /// <summary>
        /// Gets or Sets GrantAmmoOnCast
        /// </summary>
        [JsonPropertyName("grant_ammo_on_cast")]
        public bool? GrantAmmoOnCast { get { return this.GrantAmmoOnCastOption.Value; } set { this.GrantAmmoOnCastOption = new(value); } }

        /// <summary>
        /// Used to track the state of Hero
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> HeroOption { get; private set; }

        /// <summary>
        /// Gets or Sets Hero
        /// </summary>
        [JsonPropertyName("hero")]
        public int? Hero { get { return this.HeroOption.Value; } set { this.HeroOption = new(value); } }

        /// <summary>
        /// Used to track the state of Heroes
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<int>?> HeroesOption { get; private set; }

        /// <summary>
        /// Gets or Sets Heroes
        /// </summary>
        [JsonPropertyName("heroes")]
        public List<int>? Heroes { get { return this.HeroesOption.Value; } set { this.HeroesOption = new(value); } }

        /// <summary>
        /// Used to track the state of Image
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ImageOption { get; private set; }

        /// <summary>
        /// Gets or Sets Image
        /// </summary>
        [JsonPropertyName("image")]
        public string? Image { get { return this.ImageOption.Value; } set { this.ImageOption = new(value); } }

        /// <summary>
        /// Used to track the state of ImageWebp
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ImageWebpOption { get; private set; }

        /// <summary>
        /// Gets or Sets ImageWebp
        /// </summary>
        [JsonPropertyName("image_webp")]
        public string? ImageWebp { get { return this.ImageWebpOption.Value; } set { this.ImageWebpOption = new(value); } }

        /// <summary>
        /// Used to track the state of Properties
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Dictionary<string, ItemProperty>?> PropertiesOption { get; private set; }

        /// <summary>
        /// Gets or Sets Properties
        /// </summary>
        [JsonPropertyName("properties")]
        public Dictionary<string, ItemProperty>? Properties { get { return this.PropertiesOption.Value; } set { this.PropertiesOption = new(value); } }

        /// <summary>
        /// Used to track the state of StartTrained
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> StartTrainedOption { get; private set; }

        /// <summary>
        /// Gets or Sets StartTrained
        /// </summary>
        [JsonPropertyName("start_trained")]
        public bool? StartTrained { get { return this.StartTrainedOption.Value; } set { this.StartTrainedOption = new(value); } }

        /// <summary>
        /// Used to track the state of TooltipDetails
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<AbilityTooltipDetails?> TooltipDetailsOption { get; private set; }

        /// <summary>
        /// Gets or Sets TooltipDetails
        /// </summary>
        [JsonPropertyName("tooltip_details")]
        public AbilityTooltipDetails? TooltipDetails { get { return this.TooltipDetailsOption.Value; } set { this.TooltipDetailsOption = new(value); } }

        /// <summary>
        /// Used to track the state of UpdateTime
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<long?> UpdateTimeOption { get; private set; }

        /// <summary>
        /// Gets or Sets UpdateTime
        /// </summary>
        [JsonPropertyName("update_time")]
        public long? UpdateTime { get { return this.UpdateTimeOption.Value; } set { this.UpdateTimeOption = new(value); } }

        /// <summary>
        /// Used to track the state of Upgrades
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<RawAbilityUpgrade>?> UpgradesOption { get; private set; }

        /// <summary>
        /// Gets or Sets Upgrades
        /// </summary>
        [JsonPropertyName("upgrades")]
        public List<RawAbilityUpgrade>? Upgrades { get { return this.UpgradesOption.Value; } set { this.UpgradesOption = new(value); } }

        /// <summary>
        /// Used to track the state of Videos
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<AbilityVideos?> VideosOption { get; private set; }

        /// <summary>
        /// Gets or Sets Videos
        /// </summary>
        [JsonPropertyName("videos")]
        public AbilityVideos? Videos { get { return this.VideosOption.Value; } set { this.VideosOption = new(value); } }

        /// <summary>
        /// Used to track the state of WeaponInfo
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<RawItemWeaponInfoInner?> WeaponInfoOption { get; private set; }

        /// <summary>
        /// Gets or Sets WeaponInfo
        /// </summary>
        [JsonPropertyName("weapon_info")]
        public RawItemWeaponInfoInner? WeaponInfo { get { return this.WeaponInfoOption.Value; } set { this.WeaponInfoOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Ability {\n");
            sb.Append("  ClassName: ").Append(ClassName).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  AbilityType: ").Append(AbilityType).Append("\n");
            sb.Append("  Behaviours: ").Append(Behaviours).Append("\n");
            sb.Append("  BossDamageScale: ").Append(BossDamageScale).Append("\n");
            sb.Append("  DependantAbilities: ").Append(DependantAbilities).Append("\n");
            sb.Append("  DependentAbilities: ").Append(DependentAbilities).Append("\n");
            sb.Append("  GrantAmmoOnCast: ").Append(GrantAmmoOnCast).Append("\n");
            sb.Append("  Hero: ").Append(Hero).Append("\n");
            sb.Append("  Heroes: ").Append(Heroes).Append("\n");
            sb.Append("  Image: ").Append(Image).Append("\n");
            sb.Append("  ImageWebp: ").Append(ImageWebp).Append("\n");
            sb.Append("  Properties: ").Append(Properties).Append("\n");
            sb.Append("  StartTrained: ").Append(StartTrained).Append("\n");
            sb.Append("  TooltipDetails: ").Append(TooltipDetails).Append("\n");
            sb.Append("  UpdateTime: ").Append(UpdateTime).Append("\n");
            sb.Append("  Upgrades: ").Append(Upgrades).Append("\n");
            sb.Append("  Videos: ").Append(Videos).Append("\n");
            sb.Append("  WeaponInfo: ").Append(WeaponInfo).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Id (int) minimum
            if (this.Id < (int)0)
            {
                yield return new ValidationResult("Invalid value for Id, must be a value greater than or equal to 0.", new [] { "Id" });
            }

            // Hero (int) minimum
            if (this.HeroOption.IsSet && this.HeroOption.Value < (int)0)
            {
                yield return new ValidationResult("Invalid value for Hero, must be a value greater than or equal to 0.", new [] { "Hero" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Ability" />
    /// </summary>
    public partial class AbilityJsonConverter : JsonConverter<Ability>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="AbilityJsonConverter" /> class.
        /// </summary>
        public AbilityJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="Ability" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override Ability Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> className = default;
            Option<AbilityDescription?> description = default;
            Option<int?> id = default;
            Option<string?> name = default;
            Option<ItemType?> type = default;
            Option<AbilityType?> abilityType = default;
            Option<List<string>?> behaviours = default;
            Option<double?> bossDamageScale = default;
            Option<List<string>?> dependantAbilities = default;
            Option<Dictionary<string, DependantAbilities>?> dependentAbilities = default;
            Option<bool?> grantAmmoOnCast = default;
            Option<int?> hero = default;
            Option<List<int>?> heroes = default;
            Option<string?> image = default;
            Option<string?> imageWebp = default;
            Option<Dictionary<string, ItemProperty>?> properties = default;
            Option<bool?> startTrained = default;
            Option<AbilityTooltipDetails?> tooltipDetails = default;
            Option<long?> updateTime = default;
            Option<List<RawAbilityUpgrade>?> upgrades = default;
            Option<AbilityVideos?> videos = default;
            Option<RawItemWeaponInfoInner?> weaponInfo = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "class_name":
                            className = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "description":
                            description = new Option<AbilityDescription?>(JsonSerializer.Deserialize<AbilityDescription>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "id":
                            id = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "type":
                            type = new Option<ItemType?>(JsonSerializer.Deserialize<ItemType?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "ability_type":
                            abilityType = new Option<AbilityType?>(JsonSerializer.Deserialize<AbilityType?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "behaviours":
                            behaviours = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "boss_damage_scale":
                            bossDamageScale = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        case "dependant_abilities":
                            dependantAbilities = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "dependent_abilities":
                            dependentAbilities = new Option<Dictionary<string, DependantAbilities>?>(JsonSerializer.Deserialize<Dictionary<string, DependantAbilities>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "grant_ammo_on_cast":
                            grantAmmoOnCast = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "hero":
                            hero = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "heroes":
                            heroes = new Option<List<int>?>(JsonSerializer.Deserialize<List<int>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "image":
                            image = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "image_webp":
                            imageWebp = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "properties":
                            properties = new Option<Dictionary<string, ItemProperty>?>(JsonSerializer.Deserialize<Dictionary<string, ItemProperty>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "start_trained":
                            startTrained = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "tooltip_details":
                            tooltipDetails = new Option<AbilityTooltipDetails?>(JsonSerializer.Deserialize<AbilityTooltipDetails>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "update_time":
                            updateTime = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "upgrades":
                            upgrades = new Option<List<RawAbilityUpgrade>?>(JsonSerializer.Deserialize<List<RawAbilityUpgrade>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "videos":
                            videos = new Option<AbilityVideos?>(JsonSerializer.Deserialize<AbilityVideos>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "weapon_info":
                            weaponInfo = new Option<RawItemWeaponInfoInner?>(JsonSerializer.Deserialize<RawItemWeaponInfoInner>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!className.IsSet)
                throw new ArgumentException("Property is required for class Ability.", nameof(className));

            if (!description.IsSet)
                throw new ArgumentException("Property is required for class Ability.", nameof(description));

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class Ability.", nameof(id));

            if (!name.IsSet)
                throw new ArgumentException("Property is required for class Ability.", nameof(name));

            if (!type.IsSet)
                throw new ArgumentException("Property is required for class Ability.", nameof(type));

            if (className.IsSet && className.Value == null)
                throw new ArgumentNullException(nameof(className), "Property is not nullable for class Ability.");

            if (description.IsSet && description.Value == null)
                throw new ArgumentNullException(nameof(description), "Property is not nullable for class Ability.");

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class Ability.");

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class Ability.");

            if (type.IsSet && type.Value == null)
                throw new ArgumentNullException(nameof(type), "Property is not nullable for class Ability.");

            return new Ability(className.Value!, description.Value!, id.Value!.Value!, name.Value!, type.Value!.Value!, abilityType, behaviours, bossDamageScale, dependantAbilities, dependentAbilities, grantAmmoOnCast, hero, heroes, image, imageWebp, properties, startTrained, tooltipDetails, updateTime, upgrades, videos, weaponInfo);
        }

        /// <summary>
        /// Serializes a <see cref="Ability" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="ability"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, Ability ability, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, ability, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="Ability" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="ability"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, Ability ability, JsonSerializerOptions jsonSerializerOptions)
        {
            if (ability.ClassName == null)
                throw new ArgumentNullException(nameof(ability.ClassName), "Property is required for class Ability.");

            if (ability.Description == null)
                throw new ArgumentNullException(nameof(ability.Description), "Property is required for class Ability.");

            if (ability.Name == null)
                throw new ArgumentNullException(nameof(ability.Name), "Property is required for class Ability.");

            writer.WriteString("class_name", ability.ClassName);

            writer.WritePropertyName("description");
            JsonSerializer.Serialize(writer, ability.Description, jsonSerializerOptions);
            writer.WriteNumber("id", ability.Id);

            writer.WriteString("name", ability.Name);

            var typeRawValue = ItemTypeValueConverter.ToJsonValue(ability.Type);
            writer.WriteString("type", typeRawValue);

            if (ability.AbilityTypeOption.IsSet)
                if (ability.AbilityTypeOption!.Value != null)
                {
                    var abilityTypeRawValue = AbilityTypeValueConverter.ToJsonValue(ability.AbilityTypeOption.Value!.Value);
                    writer.WriteString("ability_type", abilityTypeRawValue);
                }
                else
                    writer.WriteNull("ability_type");
            if (ability.BehavioursOption.IsSet)
                if (ability.BehavioursOption.Value != null)
                {
                    writer.WritePropertyName("behaviours");
                    JsonSerializer.Serialize(writer, ability.Behaviours, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("behaviours");
            if (ability.BossDamageScaleOption.IsSet)
                if (ability.BossDamageScaleOption.Value != null)
                    writer.WriteNumber("boss_damage_scale", ability.BossDamageScaleOption.Value!.Value);
                else
                    writer.WriteNull("boss_damage_scale");

            if (ability.DependantAbilitiesOption.IsSet)
                if (ability.DependantAbilitiesOption.Value != null)
                {
                    writer.WritePropertyName("dependant_abilities");
                    JsonSerializer.Serialize(writer, ability.DependantAbilities, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("dependant_abilities");
            if (ability.DependentAbilitiesOption.IsSet)
                if (ability.DependentAbilitiesOption.Value != null)
                {
                    writer.WritePropertyName("dependent_abilities");
                    JsonSerializer.Serialize(writer, ability.DependentAbilities, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("dependent_abilities");
            if (ability.GrantAmmoOnCastOption.IsSet)
                if (ability.GrantAmmoOnCastOption.Value != null)
                    writer.WriteBoolean("grant_ammo_on_cast", ability.GrantAmmoOnCastOption.Value!.Value);
                else
                    writer.WriteNull("grant_ammo_on_cast");

            if (ability.HeroOption.IsSet)
                if (ability.HeroOption.Value != null)
                    writer.WriteNumber("hero", ability.HeroOption.Value!.Value);
                else
                    writer.WriteNull("hero");

            if (ability.HeroesOption.IsSet)
                if (ability.HeroesOption.Value != null)
                {
                    writer.WritePropertyName("heroes");
                    JsonSerializer.Serialize(writer, ability.Heroes, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("heroes");
            if (ability.ImageOption.IsSet)
                if (ability.ImageOption.Value != null)
                    writer.WriteString("image", ability.Image);
                else
                    writer.WriteNull("image");

            if (ability.ImageWebpOption.IsSet)
                if (ability.ImageWebpOption.Value != null)
                    writer.WriteString("image_webp", ability.ImageWebp);
                else
                    writer.WriteNull("image_webp");

            if (ability.PropertiesOption.IsSet)
                if (ability.PropertiesOption.Value != null)
                {
                    writer.WritePropertyName("properties");
                    JsonSerializer.Serialize(writer, ability.Properties, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("properties");
            if (ability.StartTrainedOption.IsSet)
                if (ability.StartTrainedOption.Value != null)
                    writer.WriteBoolean("start_trained", ability.StartTrainedOption.Value!.Value);
                else
                    writer.WriteNull("start_trained");

            if (ability.TooltipDetailsOption.IsSet)
                if (ability.TooltipDetailsOption.Value != null)
                {
                    writer.WritePropertyName("tooltip_details");
                    JsonSerializer.Serialize(writer, ability.TooltipDetails, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("tooltip_details");
            if (ability.UpdateTimeOption.IsSet)
                if (ability.UpdateTimeOption.Value != null)
                    writer.WriteNumber("update_time", ability.UpdateTimeOption.Value!.Value);
                else
                    writer.WriteNull("update_time");

            if (ability.UpgradesOption.IsSet)
                if (ability.UpgradesOption.Value != null)
                {
                    writer.WritePropertyName("upgrades");
                    JsonSerializer.Serialize(writer, ability.Upgrades, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("upgrades");
            if (ability.VideosOption.IsSet)
                if (ability.VideosOption.Value != null)
                {
                    writer.WritePropertyName("videos");
                    JsonSerializer.Serialize(writer, ability.Videos, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("videos");
            if (ability.WeaponInfoOption.IsSet)
                if (ability.WeaponInfoOption.Value != null)
                {
                    writer.WritePropertyName("weapon_info");
                    JsonSerializer.Serialize(writer, ability.WeaponInfo, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("weapon_info");
        }
    }
}
