<?php
/**
 * AnalyticsGameStats
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Deadlock API
 *
 * ## API Clients  We have auto generated and updated clients for many languages. You can find them here: [https://github.com/deadlock-api/openapi-clients](https://github.com/deadlock-api/openapi-clients)  ## Support the Deadlock API  Whether you're building your own database, developing data science projects, or enhancing your website with game and player analytics, the Deadlock API has the data you need.  Your sponsorship helps keep this resource open, free and future-proof for everyone. By supporting the Deadlock API, you will enable continued development, new features and reliable access for developers, analysts and streamers worldwide.  Help us continue to provide the data you need - sponsor the Deadlock API today!  **-> You can Sponsor the Deadlock API on [Patreon](https://www.patreon.com/c/user?u=68961896) or [GitHub](https://github.com/sponsors/raimannma)**  ## Disclaimer _deadlock-api.com is not endorsed by Valve and does not reflect the views or opinions of Valve or anyone officially involved in producing or managing Valve properties. Valve and all associated properties are trademarks or registered trademarks of Valve Corporation_
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * AnalyticsGameStats Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class AnalyticsGameStats implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'AnalyticsGameStats';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'abandon_rate' => 'float',
        'avg_accuracy' => 'float',
        'avg_assists' => 'float',
        'avg_boss_damage' => 'float',
        'avg_creep_damage' => 'float',
        'avg_creep_kills' => 'float',
        'avg_crit_rate' => 'float',
        'avg_damage_absorbed' => 'float',
        'avg_damage_mitigated' => 'float',
        'avg_deaths' => 'float',
        'avg_denies' => 'float',
        'avg_duration_s' => 'float',
        'avg_ending_level' => 'float',
        'avg_first_mid_boss_time_s' => 'float',
        'avg_first_objective_destroyed_time_s' => 'float',
        'avg_gold_boss' => 'float',
        'avg_gold_boss_orb' => 'float',
        'avg_gold_death_loss' => 'float',
        'avg_gold_denied' => 'float',
        'avg_gold_lane_creep' => 'float',
        'avg_gold_lane_creep_orbs' => 'float',
        'avg_gold_neutral_creep' => 'float',
        'avg_gold_neutral_creep_orbs' => 'float',
        'avg_gold_player' => 'float',
        'avg_gold_player_orbs' => 'float',
        'avg_gold_treasure' => 'float',
        'avg_heal_prevented' => 'float',
        'avg_kd_ratio' => 'float',
        'avg_kills' => 'float',
        'avg_last_hits' => 'float',
        'avg_max_health' => 'float',
        'avg_net_worth' => 'float',
        'avg_neutral_damage' => 'float',
        'avg_neutral_kills' => 'float',
        'avg_player_damage' => 'float',
        'avg_player_damage_taken' => 'float',
        'avg_player_healing' => 'float',
        'avg_possible_creeps' => 'float',
        'avg_self_healing' => 'float',
        'avg_tech_power' => 'float',
        'avg_weapon_power' => 'float',
        'bucket' => 'int',
        'mid_boss_kill_rate' => 'float',
        'team0_wins' => 'int',
        'team1_wins' => 'int',
        'total_matches' => 'int',
        'total_players' => 'int'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'abandon_rate' => 'double',
        'avg_accuracy' => 'double',
        'avg_assists' => 'double',
        'avg_boss_damage' => 'double',
        'avg_creep_damage' => 'double',
        'avg_creep_kills' => 'double',
        'avg_crit_rate' => 'double',
        'avg_damage_absorbed' => 'double',
        'avg_damage_mitigated' => 'double',
        'avg_deaths' => 'double',
        'avg_denies' => 'double',
        'avg_duration_s' => 'double',
        'avg_ending_level' => 'double',
        'avg_first_mid_boss_time_s' => 'double',
        'avg_first_objective_destroyed_time_s' => 'double',
        'avg_gold_boss' => 'double',
        'avg_gold_boss_orb' => 'double',
        'avg_gold_death_loss' => 'double',
        'avg_gold_denied' => 'double',
        'avg_gold_lane_creep' => 'double',
        'avg_gold_lane_creep_orbs' => 'double',
        'avg_gold_neutral_creep' => 'double',
        'avg_gold_neutral_creep_orbs' => 'double',
        'avg_gold_player' => 'double',
        'avg_gold_player_orbs' => 'double',
        'avg_gold_treasure' => 'double',
        'avg_heal_prevented' => 'double',
        'avg_kd_ratio' => 'double',
        'avg_kills' => 'double',
        'avg_last_hits' => 'double',
        'avg_max_health' => 'double',
        'avg_net_worth' => 'double',
        'avg_neutral_damage' => 'double',
        'avg_neutral_kills' => 'double',
        'avg_player_damage' => 'double',
        'avg_player_damage_taken' => 'double',
        'avg_player_healing' => 'double',
        'avg_possible_creeps' => 'double',
        'avg_self_healing' => 'double',
        'avg_tech_power' => 'double',
        'avg_weapon_power' => 'double',
        'bucket' => 'int32',
        'mid_boss_kill_rate' => 'double',
        'team0_wins' => 'int64',
        'team1_wins' => 'int64',
        'total_matches' => 'int64',
        'total_players' => 'int64'
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'abandon_rate' => false,
        'avg_accuracy' => false,
        'avg_assists' => false,
        'avg_boss_damage' => false,
        'avg_creep_damage' => false,
        'avg_creep_kills' => false,
        'avg_crit_rate' => false,
        'avg_damage_absorbed' => false,
        'avg_damage_mitigated' => false,
        'avg_deaths' => false,
        'avg_denies' => false,
        'avg_duration_s' => false,
        'avg_ending_level' => false,
        'avg_first_mid_boss_time_s' => false,
        'avg_first_objective_destroyed_time_s' => false,
        'avg_gold_boss' => false,
        'avg_gold_boss_orb' => false,
        'avg_gold_death_loss' => false,
        'avg_gold_denied' => false,
        'avg_gold_lane_creep' => false,
        'avg_gold_lane_creep_orbs' => false,
        'avg_gold_neutral_creep' => false,
        'avg_gold_neutral_creep_orbs' => false,
        'avg_gold_player' => false,
        'avg_gold_player_orbs' => false,
        'avg_gold_treasure' => false,
        'avg_heal_prevented' => false,
        'avg_kd_ratio' => false,
        'avg_kills' => false,
        'avg_last_hits' => false,
        'avg_max_health' => false,
        'avg_net_worth' => false,
        'avg_neutral_damage' => false,
        'avg_neutral_kills' => false,
        'avg_player_damage' => false,
        'avg_player_damage_taken' => false,
        'avg_player_healing' => false,
        'avg_possible_creeps' => false,
        'avg_self_healing' => false,
        'avg_tech_power' => false,
        'avg_weapon_power' => false,
        'bucket' => false,
        'mid_boss_kill_rate' => false,
        'team0_wins' => false,
        'team1_wins' => false,
        'total_matches' => false,
        'total_players' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'abandon_rate' => 'abandon_rate',
        'avg_accuracy' => 'avg_accuracy',
        'avg_assists' => 'avg_assists',
        'avg_boss_damage' => 'avg_boss_damage',
        'avg_creep_damage' => 'avg_creep_damage',
        'avg_creep_kills' => 'avg_creep_kills',
        'avg_crit_rate' => 'avg_crit_rate',
        'avg_damage_absorbed' => 'avg_damage_absorbed',
        'avg_damage_mitigated' => 'avg_damage_mitigated',
        'avg_deaths' => 'avg_deaths',
        'avg_denies' => 'avg_denies',
        'avg_duration_s' => 'avg_duration_s',
        'avg_ending_level' => 'avg_ending_level',
        'avg_first_mid_boss_time_s' => 'avg_first_mid_boss_time_s',
        'avg_first_objective_destroyed_time_s' => 'avg_first_objective_destroyed_time_s',
        'avg_gold_boss' => 'avg_gold_boss',
        'avg_gold_boss_orb' => 'avg_gold_boss_orb',
        'avg_gold_death_loss' => 'avg_gold_death_loss',
        'avg_gold_denied' => 'avg_gold_denied',
        'avg_gold_lane_creep' => 'avg_gold_lane_creep',
        'avg_gold_lane_creep_orbs' => 'avg_gold_lane_creep_orbs',
        'avg_gold_neutral_creep' => 'avg_gold_neutral_creep',
        'avg_gold_neutral_creep_orbs' => 'avg_gold_neutral_creep_orbs',
        'avg_gold_player' => 'avg_gold_player',
        'avg_gold_player_orbs' => 'avg_gold_player_orbs',
        'avg_gold_treasure' => 'avg_gold_treasure',
        'avg_heal_prevented' => 'avg_heal_prevented',
        'avg_kd_ratio' => 'avg_kd_ratio',
        'avg_kills' => 'avg_kills',
        'avg_last_hits' => 'avg_last_hits',
        'avg_max_health' => 'avg_max_health',
        'avg_net_worth' => 'avg_net_worth',
        'avg_neutral_damage' => 'avg_neutral_damage',
        'avg_neutral_kills' => 'avg_neutral_kills',
        'avg_player_damage' => 'avg_player_damage',
        'avg_player_damage_taken' => 'avg_player_damage_taken',
        'avg_player_healing' => 'avg_player_healing',
        'avg_possible_creeps' => 'avg_possible_creeps',
        'avg_self_healing' => 'avg_self_healing',
        'avg_tech_power' => 'avg_tech_power',
        'avg_weapon_power' => 'avg_weapon_power',
        'bucket' => 'bucket',
        'mid_boss_kill_rate' => 'mid_boss_kill_rate',
        'team0_wins' => 'team0_wins',
        'team1_wins' => 'team1_wins',
        'total_matches' => 'total_matches',
        'total_players' => 'total_players'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'abandon_rate' => 'setAbandonRate',
        'avg_accuracy' => 'setAvgAccuracy',
        'avg_assists' => 'setAvgAssists',
        'avg_boss_damage' => 'setAvgBossDamage',
        'avg_creep_damage' => 'setAvgCreepDamage',
        'avg_creep_kills' => 'setAvgCreepKills',
        'avg_crit_rate' => 'setAvgCritRate',
        'avg_damage_absorbed' => 'setAvgDamageAbsorbed',
        'avg_damage_mitigated' => 'setAvgDamageMitigated',
        'avg_deaths' => 'setAvgDeaths',
        'avg_denies' => 'setAvgDenies',
        'avg_duration_s' => 'setAvgDurationS',
        'avg_ending_level' => 'setAvgEndingLevel',
        'avg_first_mid_boss_time_s' => 'setAvgFirstMidBossTimeS',
        'avg_first_objective_destroyed_time_s' => 'setAvgFirstObjectiveDestroyedTimeS',
        'avg_gold_boss' => 'setAvgGoldBoss',
        'avg_gold_boss_orb' => 'setAvgGoldBossOrb',
        'avg_gold_death_loss' => 'setAvgGoldDeathLoss',
        'avg_gold_denied' => 'setAvgGoldDenied',
        'avg_gold_lane_creep' => 'setAvgGoldLaneCreep',
        'avg_gold_lane_creep_orbs' => 'setAvgGoldLaneCreepOrbs',
        'avg_gold_neutral_creep' => 'setAvgGoldNeutralCreep',
        'avg_gold_neutral_creep_orbs' => 'setAvgGoldNeutralCreepOrbs',
        'avg_gold_player' => 'setAvgGoldPlayer',
        'avg_gold_player_orbs' => 'setAvgGoldPlayerOrbs',
        'avg_gold_treasure' => 'setAvgGoldTreasure',
        'avg_heal_prevented' => 'setAvgHealPrevented',
        'avg_kd_ratio' => 'setAvgKdRatio',
        'avg_kills' => 'setAvgKills',
        'avg_last_hits' => 'setAvgLastHits',
        'avg_max_health' => 'setAvgMaxHealth',
        'avg_net_worth' => 'setAvgNetWorth',
        'avg_neutral_damage' => 'setAvgNeutralDamage',
        'avg_neutral_kills' => 'setAvgNeutralKills',
        'avg_player_damage' => 'setAvgPlayerDamage',
        'avg_player_damage_taken' => 'setAvgPlayerDamageTaken',
        'avg_player_healing' => 'setAvgPlayerHealing',
        'avg_possible_creeps' => 'setAvgPossibleCreeps',
        'avg_self_healing' => 'setAvgSelfHealing',
        'avg_tech_power' => 'setAvgTechPower',
        'avg_weapon_power' => 'setAvgWeaponPower',
        'bucket' => 'setBucket',
        'mid_boss_kill_rate' => 'setMidBossKillRate',
        'team0_wins' => 'setTeam0Wins',
        'team1_wins' => 'setTeam1Wins',
        'total_matches' => 'setTotalMatches',
        'total_players' => 'setTotalPlayers'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'abandon_rate' => 'getAbandonRate',
        'avg_accuracy' => 'getAvgAccuracy',
        'avg_assists' => 'getAvgAssists',
        'avg_boss_damage' => 'getAvgBossDamage',
        'avg_creep_damage' => 'getAvgCreepDamage',
        'avg_creep_kills' => 'getAvgCreepKills',
        'avg_crit_rate' => 'getAvgCritRate',
        'avg_damage_absorbed' => 'getAvgDamageAbsorbed',
        'avg_damage_mitigated' => 'getAvgDamageMitigated',
        'avg_deaths' => 'getAvgDeaths',
        'avg_denies' => 'getAvgDenies',
        'avg_duration_s' => 'getAvgDurationS',
        'avg_ending_level' => 'getAvgEndingLevel',
        'avg_first_mid_boss_time_s' => 'getAvgFirstMidBossTimeS',
        'avg_first_objective_destroyed_time_s' => 'getAvgFirstObjectiveDestroyedTimeS',
        'avg_gold_boss' => 'getAvgGoldBoss',
        'avg_gold_boss_orb' => 'getAvgGoldBossOrb',
        'avg_gold_death_loss' => 'getAvgGoldDeathLoss',
        'avg_gold_denied' => 'getAvgGoldDenied',
        'avg_gold_lane_creep' => 'getAvgGoldLaneCreep',
        'avg_gold_lane_creep_orbs' => 'getAvgGoldLaneCreepOrbs',
        'avg_gold_neutral_creep' => 'getAvgGoldNeutralCreep',
        'avg_gold_neutral_creep_orbs' => 'getAvgGoldNeutralCreepOrbs',
        'avg_gold_player' => 'getAvgGoldPlayer',
        'avg_gold_player_orbs' => 'getAvgGoldPlayerOrbs',
        'avg_gold_treasure' => 'getAvgGoldTreasure',
        'avg_heal_prevented' => 'getAvgHealPrevented',
        'avg_kd_ratio' => 'getAvgKdRatio',
        'avg_kills' => 'getAvgKills',
        'avg_last_hits' => 'getAvgLastHits',
        'avg_max_health' => 'getAvgMaxHealth',
        'avg_net_worth' => 'getAvgNetWorth',
        'avg_neutral_damage' => 'getAvgNeutralDamage',
        'avg_neutral_kills' => 'getAvgNeutralKills',
        'avg_player_damage' => 'getAvgPlayerDamage',
        'avg_player_damage_taken' => 'getAvgPlayerDamageTaken',
        'avg_player_healing' => 'getAvgPlayerHealing',
        'avg_possible_creeps' => 'getAvgPossibleCreeps',
        'avg_self_healing' => 'getAvgSelfHealing',
        'avg_tech_power' => 'getAvgTechPower',
        'avg_weapon_power' => 'getAvgWeaponPower',
        'bucket' => 'getBucket',
        'mid_boss_kill_rate' => 'getMidBossKillRate',
        'team0_wins' => 'getTeam0Wins',
        'team1_wins' => 'getTeam1Wins',
        'total_matches' => 'getTotalMatches',
        'total_players' => 'getTotalPlayers'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('abandon_rate', $data ?? [], null);
        $this->setIfExists('avg_accuracy', $data ?? [], null);
        $this->setIfExists('avg_assists', $data ?? [], null);
        $this->setIfExists('avg_boss_damage', $data ?? [], null);
        $this->setIfExists('avg_creep_damage', $data ?? [], null);
        $this->setIfExists('avg_creep_kills', $data ?? [], null);
        $this->setIfExists('avg_crit_rate', $data ?? [], null);
        $this->setIfExists('avg_damage_absorbed', $data ?? [], null);
        $this->setIfExists('avg_damage_mitigated', $data ?? [], null);
        $this->setIfExists('avg_deaths', $data ?? [], null);
        $this->setIfExists('avg_denies', $data ?? [], null);
        $this->setIfExists('avg_duration_s', $data ?? [], null);
        $this->setIfExists('avg_ending_level', $data ?? [], null);
        $this->setIfExists('avg_first_mid_boss_time_s', $data ?? [], null);
        $this->setIfExists('avg_first_objective_destroyed_time_s', $data ?? [], null);
        $this->setIfExists('avg_gold_boss', $data ?? [], null);
        $this->setIfExists('avg_gold_boss_orb', $data ?? [], null);
        $this->setIfExists('avg_gold_death_loss', $data ?? [], null);
        $this->setIfExists('avg_gold_denied', $data ?? [], null);
        $this->setIfExists('avg_gold_lane_creep', $data ?? [], null);
        $this->setIfExists('avg_gold_lane_creep_orbs', $data ?? [], null);
        $this->setIfExists('avg_gold_neutral_creep', $data ?? [], null);
        $this->setIfExists('avg_gold_neutral_creep_orbs', $data ?? [], null);
        $this->setIfExists('avg_gold_player', $data ?? [], null);
        $this->setIfExists('avg_gold_player_orbs', $data ?? [], null);
        $this->setIfExists('avg_gold_treasure', $data ?? [], null);
        $this->setIfExists('avg_heal_prevented', $data ?? [], null);
        $this->setIfExists('avg_kd_ratio', $data ?? [], null);
        $this->setIfExists('avg_kills', $data ?? [], null);
        $this->setIfExists('avg_last_hits', $data ?? [], null);
        $this->setIfExists('avg_max_health', $data ?? [], null);
        $this->setIfExists('avg_net_worth', $data ?? [], null);
        $this->setIfExists('avg_neutral_damage', $data ?? [], null);
        $this->setIfExists('avg_neutral_kills', $data ?? [], null);
        $this->setIfExists('avg_player_damage', $data ?? [], null);
        $this->setIfExists('avg_player_damage_taken', $data ?? [], null);
        $this->setIfExists('avg_player_healing', $data ?? [], null);
        $this->setIfExists('avg_possible_creeps', $data ?? [], null);
        $this->setIfExists('avg_self_healing', $data ?? [], null);
        $this->setIfExists('avg_tech_power', $data ?? [], null);
        $this->setIfExists('avg_weapon_power', $data ?? [], null);
        $this->setIfExists('bucket', $data ?? [], null);
        $this->setIfExists('mid_boss_kill_rate', $data ?? [], null);
        $this->setIfExists('team0_wins', $data ?? [], null);
        $this->setIfExists('team1_wins', $data ?? [], null);
        $this->setIfExists('total_matches', $data ?? [], null);
        $this->setIfExists('total_players', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['abandon_rate'] === null) {
            $invalidProperties[] = "'abandon_rate' can't be null";
        }
        if ($this->container['avg_accuracy'] === null) {
            $invalidProperties[] = "'avg_accuracy' can't be null";
        }
        if ($this->container['avg_assists'] === null) {
            $invalidProperties[] = "'avg_assists' can't be null";
        }
        if ($this->container['avg_boss_damage'] === null) {
            $invalidProperties[] = "'avg_boss_damage' can't be null";
        }
        if ($this->container['avg_creep_damage'] === null) {
            $invalidProperties[] = "'avg_creep_damage' can't be null";
        }
        if ($this->container['avg_creep_kills'] === null) {
            $invalidProperties[] = "'avg_creep_kills' can't be null";
        }
        if ($this->container['avg_crit_rate'] === null) {
            $invalidProperties[] = "'avg_crit_rate' can't be null";
        }
        if ($this->container['avg_damage_absorbed'] === null) {
            $invalidProperties[] = "'avg_damage_absorbed' can't be null";
        }
        if ($this->container['avg_damage_mitigated'] === null) {
            $invalidProperties[] = "'avg_damage_mitigated' can't be null";
        }
        if ($this->container['avg_deaths'] === null) {
            $invalidProperties[] = "'avg_deaths' can't be null";
        }
        if ($this->container['avg_denies'] === null) {
            $invalidProperties[] = "'avg_denies' can't be null";
        }
        if ($this->container['avg_duration_s'] === null) {
            $invalidProperties[] = "'avg_duration_s' can't be null";
        }
        if ($this->container['avg_ending_level'] === null) {
            $invalidProperties[] = "'avg_ending_level' can't be null";
        }
        if ($this->container['avg_first_mid_boss_time_s'] === null) {
            $invalidProperties[] = "'avg_first_mid_boss_time_s' can't be null";
        }
        if ($this->container['avg_first_objective_destroyed_time_s'] === null) {
            $invalidProperties[] = "'avg_first_objective_destroyed_time_s' can't be null";
        }
        if ($this->container['avg_gold_boss'] === null) {
            $invalidProperties[] = "'avg_gold_boss' can't be null";
        }
        if ($this->container['avg_gold_boss_orb'] === null) {
            $invalidProperties[] = "'avg_gold_boss_orb' can't be null";
        }
        if ($this->container['avg_gold_death_loss'] === null) {
            $invalidProperties[] = "'avg_gold_death_loss' can't be null";
        }
        if ($this->container['avg_gold_denied'] === null) {
            $invalidProperties[] = "'avg_gold_denied' can't be null";
        }
        if ($this->container['avg_gold_lane_creep'] === null) {
            $invalidProperties[] = "'avg_gold_lane_creep' can't be null";
        }
        if ($this->container['avg_gold_lane_creep_orbs'] === null) {
            $invalidProperties[] = "'avg_gold_lane_creep_orbs' can't be null";
        }
        if ($this->container['avg_gold_neutral_creep'] === null) {
            $invalidProperties[] = "'avg_gold_neutral_creep' can't be null";
        }
        if ($this->container['avg_gold_neutral_creep_orbs'] === null) {
            $invalidProperties[] = "'avg_gold_neutral_creep_orbs' can't be null";
        }
        if ($this->container['avg_gold_player'] === null) {
            $invalidProperties[] = "'avg_gold_player' can't be null";
        }
        if ($this->container['avg_gold_player_orbs'] === null) {
            $invalidProperties[] = "'avg_gold_player_orbs' can't be null";
        }
        if ($this->container['avg_gold_treasure'] === null) {
            $invalidProperties[] = "'avg_gold_treasure' can't be null";
        }
        if ($this->container['avg_heal_prevented'] === null) {
            $invalidProperties[] = "'avg_heal_prevented' can't be null";
        }
        if ($this->container['avg_kd_ratio'] === null) {
            $invalidProperties[] = "'avg_kd_ratio' can't be null";
        }
        if ($this->container['avg_kills'] === null) {
            $invalidProperties[] = "'avg_kills' can't be null";
        }
        if ($this->container['avg_last_hits'] === null) {
            $invalidProperties[] = "'avg_last_hits' can't be null";
        }
        if ($this->container['avg_max_health'] === null) {
            $invalidProperties[] = "'avg_max_health' can't be null";
        }
        if ($this->container['avg_net_worth'] === null) {
            $invalidProperties[] = "'avg_net_worth' can't be null";
        }
        if ($this->container['avg_neutral_damage'] === null) {
            $invalidProperties[] = "'avg_neutral_damage' can't be null";
        }
        if ($this->container['avg_neutral_kills'] === null) {
            $invalidProperties[] = "'avg_neutral_kills' can't be null";
        }
        if ($this->container['avg_player_damage'] === null) {
            $invalidProperties[] = "'avg_player_damage' can't be null";
        }
        if ($this->container['avg_player_damage_taken'] === null) {
            $invalidProperties[] = "'avg_player_damage_taken' can't be null";
        }
        if ($this->container['avg_player_healing'] === null) {
            $invalidProperties[] = "'avg_player_healing' can't be null";
        }
        if ($this->container['avg_possible_creeps'] === null) {
            $invalidProperties[] = "'avg_possible_creeps' can't be null";
        }
        if ($this->container['avg_self_healing'] === null) {
            $invalidProperties[] = "'avg_self_healing' can't be null";
        }
        if ($this->container['avg_tech_power'] === null) {
            $invalidProperties[] = "'avg_tech_power' can't be null";
        }
        if ($this->container['avg_weapon_power'] === null) {
            $invalidProperties[] = "'avg_weapon_power' can't be null";
        }
        if ($this->container['bucket'] === null) {
            $invalidProperties[] = "'bucket' can't be null";
        }
        if (($this->container['bucket'] < 0)) {
            $invalidProperties[] = "invalid value for 'bucket', must be bigger than or equal to 0.";
        }

        if ($this->container['mid_boss_kill_rate'] === null) {
            $invalidProperties[] = "'mid_boss_kill_rate' can't be null";
        }
        if ($this->container['team0_wins'] === null) {
            $invalidProperties[] = "'team0_wins' can't be null";
        }
        if (($this->container['team0_wins'] < 0)) {
            $invalidProperties[] = "invalid value for 'team0_wins', must be bigger than or equal to 0.";
        }

        if ($this->container['team1_wins'] === null) {
            $invalidProperties[] = "'team1_wins' can't be null";
        }
        if (($this->container['team1_wins'] < 0)) {
            $invalidProperties[] = "invalid value for 'team1_wins', must be bigger than or equal to 0.";
        }

        if ($this->container['total_matches'] === null) {
            $invalidProperties[] = "'total_matches' can't be null";
        }
        if (($this->container['total_matches'] < 0)) {
            $invalidProperties[] = "invalid value for 'total_matches', must be bigger than or equal to 0.";
        }

        if ($this->container['total_players'] === null) {
            $invalidProperties[] = "'total_players' can't be null";
        }
        if (($this->container['total_players'] < 0)) {
            $invalidProperties[] = "invalid value for 'total_players', must be bigger than or equal to 0.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets abandon_rate
     *
     * @return float
     */
    public function getAbandonRate()
    {
        return $this->container['abandon_rate'];
    }

    /**
     * Sets abandon_rate
     *
     * @param float $abandon_rate abandon_rate
     *
     * @return self
     */
    public function setAbandonRate($abandon_rate)
    {
        if (is_null($abandon_rate)) {
            throw new \InvalidArgumentException('non-nullable abandon_rate cannot be null');
        }
        $this->container['abandon_rate'] = $abandon_rate;

        return $this;
    }

    /**
     * Gets avg_accuracy
     *
     * @return float
     */
    public function getAvgAccuracy()
    {
        return $this->container['avg_accuracy'];
    }

    /**
     * Sets avg_accuracy
     *
     * @param float $avg_accuracy avg_accuracy
     *
     * @return self
     */
    public function setAvgAccuracy($avg_accuracy)
    {
        if (is_null($avg_accuracy)) {
            throw new \InvalidArgumentException('non-nullable avg_accuracy cannot be null');
        }
        $this->container['avg_accuracy'] = $avg_accuracy;

        return $this;
    }

    /**
     * Gets avg_assists
     *
     * @return float
     */
    public function getAvgAssists()
    {
        return $this->container['avg_assists'];
    }

    /**
     * Sets avg_assists
     *
     * @param float $avg_assists avg_assists
     *
     * @return self
     */
    public function setAvgAssists($avg_assists)
    {
        if (is_null($avg_assists)) {
            throw new \InvalidArgumentException('non-nullable avg_assists cannot be null');
        }
        $this->container['avg_assists'] = $avg_assists;

        return $this;
    }

    /**
     * Gets avg_boss_damage
     *
     * @return float
     */
    public function getAvgBossDamage()
    {
        return $this->container['avg_boss_damage'];
    }

    /**
     * Sets avg_boss_damage
     *
     * @param float $avg_boss_damage avg_boss_damage
     *
     * @return self
     */
    public function setAvgBossDamage($avg_boss_damage)
    {
        if (is_null($avg_boss_damage)) {
            throw new \InvalidArgumentException('non-nullable avg_boss_damage cannot be null');
        }
        $this->container['avg_boss_damage'] = $avg_boss_damage;

        return $this;
    }

    /**
     * Gets avg_creep_damage
     *
     * @return float
     */
    public function getAvgCreepDamage()
    {
        return $this->container['avg_creep_damage'];
    }

    /**
     * Sets avg_creep_damage
     *
     * @param float $avg_creep_damage avg_creep_damage
     *
     * @return self
     */
    public function setAvgCreepDamage($avg_creep_damage)
    {
        if (is_null($avg_creep_damage)) {
            throw new \InvalidArgumentException('non-nullable avg_creep_damage cannot be null');
        }
        $this->container['avg_creep_damage'] = $avg_creep_damage;

        return $this;
    }

    /**
     * Gets avg_creep_kills
     *
     * @return float
     */
    public function getAvgCreepKills()
    {
        return $this->container['avg_creep_kills'];
    }

    /**
     * Sets avg_creep_kills
     *
     * @param float $avg_creep_kills avg_creep_kills
     *
     * @return self
     */
    public function setAvgCreepKills($avg_creep_kills)
    {
        if (is_null($avg_creep_kills)) {
            throw new \InvalidArgumentException('non-nullable avg_creep_kills cannot be null');
        }
        $this->container['avg_creep_kills'] = $avg_creep_kills;

        return $this;
    }

    /**
     * Gets avg_crit_rate
     *
     * @return float
     */
    public function getAvgCritRate()
    {
        return $this->container['avg_crit_rate'];
    }

    /**
     * Sets avg_crit_rate
     *
     * @param float $avg_crit_rate avg_crit_rate
     *
     * @return self
     */
    public function setAvgCritRate($avg_crit_rate)
    {
        if (is_null($avg_crit_rate)) {
            throw new \InvalidArgumentException('non-nullable avg_crit_rate cannot be null');
        }
        $this->container['avg_crit_rate'] = $avg_crit_rate;

        return $this;
    }

    /**
     * Gets avg_damage_absorbed
     *
     * @return float
     */
    public function getAvgDamageAbsorbed()
    {
        return $this->container['avg_damage_absorbed'];
    }

    /**
     * Sets avg_damage_absorbed
     *
     * @param float $avg_damage_absorbed avg_damage_absorbed
     *
     * @return self
     */
    public function setAvgDamageAbsorbed($avg_damage_absorbed)
    {
        if (is_null($avg_damage_absorbed)) {
            throw new \InvalidArgumentException('non-nullable avg_damage_absorbed cannot be null');
        }
        $this->container['avg_damage_absorbed'] = $avg_damage_absorbed;

        return $this;
    }

    /**
     * Gets avg_damage_mitigated
     *
     * @return float
     */
    public function getAvgDamageMitigated()
    {
        return $this->container['avg_damage_mitigated'];
    }

    /**
     * Sets avg_damage_mitigated
     *
     * @param float $avg_damage_mitigated avg_damage_mitigated
     *
     * @return self
     */
    public function setAvgDamageMitigated($avg_damage_mitigated)
    {
        if (is_null($avg_damage_mitigated)) {
            throw new \InvalidArgumentException('non-nullable avg_damage_mitigated cannot be null');
        }
        $this->container['avg_damage_mitigated'] = $avg_damage_mitigated;

        return $this;
    }

    /**
     * Gets avg_deaths
     *
     * @return float
     */
    public function getAvgDeaths()
    {
        return $this->container['avg_deaths'];
    }

    /**
     * Sets avg_deaths
     *
     * @param float $avg_deaths avg_deaths
     *
     * @return self
     */
    public function setAvgDeaths($avg_deaths)
    {
        if (is_null($avg_deaths)) {
            throw new \InvalidArgumentException('non-nullable avg_deaths cannot be null');
        }
        $this->container['avg_deaths'] = $avg_deaths;

        return $this;
    }

    /**
     * Gets avg_denies
     *
     * @return float
     */
    public function getAvgDenies()
    {
        return $this->container['avg_denies'];
    }

    /**
     * Sets avg_denies
     *
     * @param float $avg_denies avg_denies
     *
     * @return self
     */
    public function setAvgDenies($avg_denies)
    {
        if (is_null($avg_denies)) {
            throw new \InvalidArgumentException('non-nullable avg_denies cannot be null');
        }
        $this->container['avg_denies'] = $avg_denies;

        return $this;
    }

    /**
     * Gets avg_duration_s
     *
     * @return float
     */
    public function getAvgDurationS()
    {
        return $this->container['avg_duration_s'];
    }

    /**
     * Sets avg_duration_s
     *
     * @param float $avg_duration_s avg_duration_s
     *
     * @return self
     */
    public function setAvgDurationS($avg_duration_s)
    {
        if (is_null($avg_duration_s)) {
            throw new \InvalidArgumentException('non-nullable avg_duration_s cannot be null');
        }
        $this->container['avg_duration_s'] = $avg_duration_s;

        return $this;
    }

    /**
     * Gets avg_ending_level
     *
     * @return float
     */
    public function getAvgEndingLevel()
    {
        return $this->container['avg_ending_level'];
    }

    /**
     * Sets avg_ending_level
     *
     * @param float $avg_ending_level avg_ending_level
     *
     * @return self
     */
    public function setAvgEndingLevel($avg_ending_level)
    {
        if (is_null($avg_ending_level)) {
            throw new \InvalidArgumentException('non-nullable avg_ending_level cannot be null');
        }
        $this->container['avg_ending_level'] = $avg_ending_level;

        return $this;
    }

    /**
     * Gets avg_first_mid_boss_time_s
     *
     * @return float
     */
    public function getAvgFirstMidBossTimeS()
    {
        return $this->container['avg_first_mid_boss_time_s'];
    }

    /**
     * Sets avg_first_mid_boss_time_s
     *
     * @param float $avg_first_mid_boss_time_s avg_first_mid_boss_time_s
     *
     * @return self
     */
    public function setAvgFirstMidBossTimeS($avg_first_mid_boss_time_s)
    {
        if (is_null($avg_first_mid_boss_time_s)) {
            throw new \InvalidArgumentException('non-nullable avg_first_mid_boss_time_s cannot be null');
        }
        $this->container['avg_first_mid_boss_time_s'] = $avg_first_mid_boss_time_s;

        return $this;
    }

    /**
     * Gets avg_first_objective_destroyed_time_s
     *
     * @return float
     */
    public function getAvgFirstObjectiveDestroyedTimeS()
    {
        return $this->container['avg_first_objective_destroyed_time_s'];
    }

    /**
     * Sets avg_first_objective_destroyed_time_s
     *
     * @param float $avg_first_objective_destroyed_time_s avg_first_objective_destroyed_time_s
     *
     * @return self
     */
    public function setAvgFirstObjectiveDestroyedTimeS($avg_first_objective_destroyed_time_s)
    {
        if (is_null($avg_first_objective_destroyed_time_s)) {
            throw new \InvalidArgumentException('non-nullable avg_first_objective_destroyed_time_s cannot be null');
        }
        $this->container['avg_first_objective_destroyed_time_s'] = $avg_first_objective_destroyed_time_s;

        return $this;
    }

    /**
     * Gets avg_gold_boss
     *
     * @return float
     */
    public function getAvgGoldBoss()
    {
        return $this->container['avg_gold_boss'];
    }

    /**
     * Sets avg_gold_boss
     *
     * @param float $avg_gold_boss avg_gold_boss
     *
     * @return self
     */
    public function setAvgGoldBoss($avg_gold_boss)
    {
        if (is_null($avg_gold_boss)) {
            throw new \InvalidArgumentException('non-nullable avg_gold_boss cannot be null');
        }
        $this->container['avg_gold_boss'] = $avg_gold_boss;

        return $this;
    }

    /**
     * Gets avg_gold_boss_orb
     *
     * @return float
     */
    public function getAvgGoldBossOrb()
    {
        return $this->container['avg_gold_boss_orb'];
    }

    /**
     * Sets avg_gold_boss_orb
     *
     * @param float $avg_gold_boss_orb avg_gold_boss_orb
     *
     * @return self
     */
    public function setAvgGoldBossOrb($avg_gold_boss_orb)
    {
        if (is_null($avg_gold_boss_orb)) {
            throw new \InvalidArgumentException('non-nullable avg_gold_boss_orb cannot be null');
        }
        $this->container['avg_gold_boss_orb'] = $avg_gold_boss_orb;

        return $this;
    }

    /**
     * Gets avg_gold_death_loss
     *
     * @return float
     */
    public function getAvgGoldDeathLoss()
    {
        return $this->container['avg_gold_death_loss'];
    }

    /**
     * Sets avg_gold_death_loss
     *
     * @param float $avg_gold_death_loss avg_gold_death_loss
     *
     * @return self
     */
    public function setAvgGoldDeathLoss($avg_gold_death_loss)
    {
        if (is_null($avg_gold_death_loss)) {
            throw new \InvalidArgumentException('non-nullable avg_gold_death_loss cannot be null');
        }
        $this->container['avg_gold_death_loss'] = $avg_gold_death_loss;

        return $this;
    }

    /**
     * Gets avg_gold_denied
     *
     * @return float
     */
    public function getAvgGoldDenied()
    {
        return $this->container['avg_gold_denied'];
    }

    /**
     * Sets avg_gold_denied
     *
     * @param float $avg_gold_denied avg_gold_denied
     *
     * @return self
     */
    public function setAvgGoldDenied($avg_gold_denied)
    {
        if (is_null($avg_gold_denied)) {
            throw new \InvalidArgumentException('non-nullable avg_gold_denied cannot be null');
        }
        $this->container['avg_gold_denied'] = $avg_gold_denied;

        return $this;
    }

    /**
     * Gets avg_gold_lane_creep
     *
     * @return float
     */
    public function getAvgGoldLaneCreep()
    {
        return $this->container['avg_gold_lane_creep'];
    }

    /**
     * Sets avg_gold_lane_creep
     *
     * @param float $avg_gold_lane_creep avg_gold_lane_creep
     *
     * @return self
     */
    public function setAvgGoldLaneCreep($avg_gold_lane_creep)
    {
        if (is_null($avg_gold_lane_creep)) {
            throw new \InvalidArgumentException('non-nullable avg_gold_lane_creep cannot be null');
        }
        $this->container['avg_gold_lane_creep'] = $avg_gold_lane_creep;

        return $this;
    }

    /**
     * Gets avg_gold_lane_creep_orbs
     *
     * @return float
     */
    public function getAvgGoldLaneCreepOrbs()
    {
        return $this->container['avg_gold_lane_creep_orbs'];
    }

    /**
     * Sets avg_gold_lane_creep_orbs
     *
     * @param float $avg_gold_lane_creep_orbs avg_gold_lane_creep_orbs
     *
     * @return self
     */
    public function setAvgGoldLaneCreepOrbs($avg_gold_lane_creep_orbs)
    {
        if (is_null($avg_gold_lane_creep_orbs)) {
            throw new \InvalidArgumentException('non-nullable avg_gold_lane_creep_orbs cannot be null');
        }
        $this->container['avg_gold_lane_creep_orbs'] = $avg_gold_lane_creep_orbs;

        return $this;
    }

    /**
     * Gets avg_gold_neutral_creep
     *
     * @return float
     */
    public function getAvgGoldNeutralCreep()
    {
        return $this->container['avg_gold_neutral_creep'];
    }

    /**
     * Sets avg_gold_neutral_creep
     *
     * @param float $avg_gold_neutral_creep avg_gold_neutral_creep
     *
     * @return self
     */
    public function setAvgGoldNeutralCreep($avg_gold_neutral_creep)
    {
        if (is_null($avg_gold_neutral_creep)) {
            throw new \InvalidArgumentException('non-nullable avg_gold_neutral_creep cannot be null');
        }
        $this->container['avg_gold_neutral_creep'] = $avg_gold_neutral_creep;

        return $this;
    }

    /**
     * Gets avg_gold_neutral_creep_orbs
     *
     * @return float
     */
    public function getAvgGoldNeutralCreepOrbs()
    {
        return $this->container['avg_gold_neutral_creep_orbs'];
    }

    /**
     * Sets avg_gold_neutral_creep_orbs
     *
     * @param float $avg_gold_neutral_creep_orbs avg_gold_neutral_creep_orbs
     *
     * @return self
     */
    public function setAvgGoldNeutralCreepOrbs($avg_gold_neutral_creep_orbs)
    {
        if (is_null($avg_gold_neutral_creep_orbs)) {
            throw new \InvalidArgumentException('non-nullable avg_gold_neutral_creep_orbs cannot be null');
        }
        $this->container['avg_gold_neutral_creep_orbs'] = $avg_gold_neutral_creep_orbs;

        return $this;
    }

    /**
     * Gets avg_gold_player
     *
     * @return float
     */
    public function getAvgGoldPlayer()
    {
        return $this->container['avg_gold_player'];
    }

    /**
     * Sets avg_gold_player
     *
     * @param float $avg_gold_player avg_gold_player
     *
     * @return self
     */
    public function setAvgGoldPlayer($avg_gold_player)
    {
        if (is_null($avg_gold_player)) {
            throw new \InvalidArgumentException('non-nullable avg_gold_player cannot be null');
        }
        $this->container['avg_gold_player'] = $avg_gold_player;

        return $this;
    }

    /**
     * Gets avg_gold_player_orbs
     *
     * @return float
     */
    public function getAvgGoldPlayerOrbs()
    {
        return $this->container['avg_gold_player_orbs'];
    }

    /**
     * Sets avg_gold_player_orbs
     *
     * @param float $avg_gold_player_orbs avg_gold_player_orbs
     *
     * @return self
     */
    public function setAvgGoldPlayerOrbs($avg_gold_player_orbs)
    {
        if (is_null($avg_gold_player_orbs)) {
            throw new \InvalidArgumentException('non-nullable avg_gold_player_orbs cannot be null');
        }
        $this->container['avg_gold_player_orbs'] = $avg_gold_player_orbs;

        return $this;
    }

    /**
     * Gets avg_gold_treasure
     *
     * @return float
     */
    public function getAvgGoldTreasure()
    {
        return $this->container['avg_gold_treasure'];
    }

    /**
     * Sets avg_gold_treasure
     *
     * @param float $avg_gold_treasure avg_gold_treasure
     *
     * @return self
     */
    public function setAvgGoldTreasure($avg_gold_treasure)
    {
        if (is_null($avg_gold_treasure)) {
            throw new \InvalidArgumentException('non-nullable avg_gold_treasure cannot be null');
        }
        $this->container['avg_gold_treasure'] = $avg_gold_treasure;

        return $this;
    }

    /**
     * Gets avg_heal_prevented
     *
     * @return float
     */
    public function getAvgHealPrevented()
    {
        return $this->container['avg_heal_prevented'];
    }

    /**
     * Sets avg_heal_prevented
     *
     * @param float $avg_heal_prevented avg_heal_prevented
     *
     * @return self
     */
    public function setAvgHealPrevented($avg_heal_prevented)
    {
        if (is_null($avg_heal_prevented)) {
            throw new \InvalidArgumentException('non-nullable avg_heal_prevented cannot be null');
        }
        $this->container['avg_heal_prevented'] = $avg_heal_prevented;

        return $this;
    }

    /**
     * Gets avg_kd_ratio
     *
     * @return float
     */
    public function getAvgKdRatio()
    {
        return $this->container['avg_kd_ratio'];
    }

    /**
     * Sets avg_kd_ratio
     *
     * @param float $avg_kd_ratio avg_kd_ratio
     *
     * @return self
     */
    public function setAvgKdRatio($avg_kd_ratio)
    {
        if (is_null($avg_kd_ratio)) {
            throw new \InvalidArgumentException('non-nullable avg_kd_ratio cannot be null');
        }
        $this->container['avg_kd_ratio'] = $avg_kd_ratio;

        return $this;
    }

    /**
     * Gets avg_kills
     *
     * @return float
     */
    public function getAvgKills()
    {
        return $this->container['avg_kills'];
    }

    /**
     * Sets avg_kills
     *
     * @param float $avg_kills avg_kills
     *
     * @return self
     */
    public function setAvgKills($avg_kills)
    {
        if (is_null($avg_kills)) {
            throw new \InvalidArgumentException('non-nullable avg_kills cannot be null');
        }
        $this->container['avg_kills'] = $avg_kills;

        return $this;
    }

    /**
     * Gets avg_last_hits
     *
     * @return float
     */
    public function getAvgLastHits()
    {
        return $this->container['avg_last_hits'];
    }

    /**
     * Sets avg_last_hits
     *
     * @param float $avg_last_hits avg_last_hits
     *
     * @return self
     */
    public function setAvgLastHits($avg_last_hits)
    {
        if (is_null($avg_last_hits)) {
            throw new \InvalidArgumentException('non-nullable avg_last_hits cannot be null');
        }
        $this->container['avg_last_hits'] = $avg_last_hits;

        return $this;
    }

    /**
     * Gets avg_max_health
     *
     * @return float
     */
    public function getAvgMaxHealth()
    {
        return $this->container['avg_max_health'];
    }

    /**
     * Sets avg_max_health
     *
     * @param float $avg_max_health avg_max_health
     *
     * @return self
     */
    public function setAvgMaxHealth($avg_max_health)
    {
        if (is_null($avg_max_health)) {
            throw new \InvalidArgumentException('non-nullable avg_max_health cannot be null');
        }
        $this->container['avg_max_health'] = $avg_max_health;

        return $this;
    }

    /**
     * Gets avg_net_worth
     *
     * @return float
     */
    public function getAvgNetWorth()
    {
        return $this->container['avg_net_worth'];
    }

    /**
     * Sets avg_net_worth
     *
     * @param float $avg_net_worth avg_net_worth
     *
     * @return self
     */
    public function setAvgNetWorth($avg_net_worth)
    {
        if (is_null($avg_net_worth)) {
            throw new \InvalidArgumentException('non-nullable avg_net_worth cannot be null');
        }
        $this->container['avg_net_worth'] = $avg_net_worth;

        return $this;
    }

    /**
     * Gets avg_neutral_damage
     *
     * @return float
     */
    public function getAvgNeutralDamage()
    {
        return $this->container['avg_neutral_damage'];
    }

    /**
     * Sets avg_neutral_damage
     *
     * @param float $avg_neutral_damage avg_neutral_damage
     *
     * @return self
     */
    public function setAvgNeutralDamage($avg_neutral_damage)
    {
        if (is_null($avg_neutral_damage)) {
            throw new \InvalidArgumentException('non-nullable avg_neutral_damage cannot be null');
        }
        $this->container['avg_neutral_damage'] = $avg_neutral_damage;

        return $this;
    }

    /**
     * Gets avg_neutral_kills
     *
     * @return float
     */
    public function getAvgNeutralKills()
    {
        return $this->container['avg_neutral_kills'];
    }

    /**
     * Sets avg_neutral_kills
     *
     * @param float $avg_neutral_kills avg_neutral_kills
     *
     * @return self
     */
    public function setAvgNeutralKills($avg_neutral_kills)
    {
        if (is_null($avg_neutral_kills)) {
            throw new \InvalidArgumentException('non-nullable avg_neutral_kills cannot be null');
        }
        $this->container['avg_neutral_kills'] = $avg_neutral_kills;

        return $this;
    }

    /**
     * Gets avg_player_damage
     *
     * @return float
     */
    public function getAvgPlayerDamage()
    {
        return $this->container['avg_player_damage'];
    }

    /**
     * Sets avg_player_damage
     *
     * @param float $avg_player_damage avg_player_damage
     *
     * @return self
     */
    public function setAvgPlayerDamage($avg_player_damage)
    {
        if (is_null($avg_player_damage)) {
            throw new \InvalidArgumentException('non-nullable avg_player_damage cannot be null');
        }
        $this->container['avg_player_damage'] = $avg_player_damage;

        return $this;
    }

    /**
     * Gets avg_player_damage_taken
     *
     * @return float
     */
    public function getAvgPlayerDamageTaken()
    {
        return $this->container['avg_player_damage_taken'];
    }

    /**
     * Sets avg_player_damage_taken
     *
     * @param float $avg_player_damage_taken avg_player_damage_taken
     *
     * @return self
     */
    public function setAvgPlayerDamageTaken($avg_player_damage_taken)
    {
        if (is_null($avg_player_damage_taken)) {
            throw new \InvalidArgumentException('non-nullable avg_player_damage_taken cannot be null');
        }
        $this->container['avg_player_damage_taken'] = $avg_player_damage_taken;

        return $this;
    }

    /**
     * Gets avg_player_healing
     *
     * @return float
     */
    public function getAvgPlayerHealing()
    {
        return $this->container['avg_player_healing'];
    }

    /**
     * Sets avg_player_healing
     *
     * @param float $avg_player_healing avg_player_healing
     *
     * @return self
     */
    public function setAvgPlayerHealing($avg_player_healing)
    {
        if (is_null($avg_player_healing)) {
            throw new \InvalidArgumentException('non-nullable avg_player_healing cannot be null');
        }
        $this->container['avg_player_healing'] = $avg_player_healing;

        return $this;
    }

    /**
     * Gets avg_possible_creeps
     *
     * @return float
     */
    public function getAvgPossibleCreeps()
    {
        return $this->container['avg_possible_creeps'];
    }

    /**
     * Sets avg_possible_creeps
     *
     * @param float $avg_possible_creeps avg_possible_creeps
     *
     * @return self
     */
    public function setAvgPossibleCreeps($avg_possible_creeps)
    {
        if (is_null($avg_possible_creeps)) {
            throw new \InvalidArgumentException('non-nullable avg_possible_creeps cannot be null');
        }
        $this->container['avg_possible_creeps'] = $avg_possible_creeps;

        return $this;
    }

    /**
     * Gets avg_self_healing
     *
     * @return float
     */
    public function getAvgSelfHealing()
    {
        return $this->container['avg_self_healing'];
    }

    /**
     * Sets avg_self_healing
     *
     * @param float $avg_self_healing avg_self_healing
     *
     * @return self
     */
    public function setAvgSelfHealing($avg_self_healing)
    {
        if (is_null($avg_self_healing)) {
            throw new \InvalidArgumentException('non-nullable avg_self_healing cannot be null');
        }
        $this->container['avg_self_healing'] = $avg_self_healing;

        return $this;
    }

    /**
     * Gets avg_tech_power
     *
     * @return float
     */
    public function getAvgTechPower()
    {
        return $this->container['avg_tech_power'];
    }

    /**
     * Sets avg_tech_power
     *
     * @param float $avg_tech_power avg_tech_power
     *
     * @return self
     */
    public function setAvgTechPower($avg_tech_power)
    {
        if (is_null($avg_tech_power)) {
            throw new \InvalidArgumentException('non-nullable avg_tech_power cannot be null');
        }
        $this->container['avg_tech_power'] = $avg_tech_power;

        return $this;
    }

    /**
     * Gets avg_weapon_power
     *
     * @return float
     */
    public function getAvgWeaponPower()
    {
        return $this->container['avg_weapon_power'];
    }

    /**
     * Sets avg_weapon_power
     *
     * @param float $avg_weapon_power avg_weapon_power
     *
     * @return self
     */
    public function setAvgWeaponPower($avg_weapon_power)
    {
        if (is_null($avg_weapon_power)) {
            throw new \InvalidArgumentException('non-nullable avg_weapon_power cannot be null');
        }
        $this->container['avg_weapon_power'] = $avg_weapon_power;

        return $this;
    }

    /**
     * Gets bucket
     *
     * @return int
     */
    public function getBucket()
    {
        return $this->container['bucket'];
    }

    /**
     * Sets bucket
     *
     * @param int $bucket bucket
     *
     * @return self
     */
    public function setBucket($bucket)
    {
        if (is_null($bucket)) {
            throw new \InvalidArgumentException('non-nullable bucket cannot be null');
        }
        if (($bucket < 0)) {
            throw new \InvalidArgumentException('invalid value for $bucket when calling AnalyticsGameStats., must be bigger than or equal to 0.');
        }

        $this->container['bucket'] = $bucket;

        return $this;
    }

    /**
     * Gets mid_boss_kill_rate
     *
     * @return float
     */
    public function getMidBossKillRate()
    {
        return $this->container['mid_boss_kill_rate'];
    }

    /**
     * Sets mid_boss_kill_rate
     *
     * @param float $mid_boss_kill_rate mid_boss_kill_rate
     *
     * @return self
     */
    public function setMidBossKillRate($mid_boss_kill_rate)
    {
        if (is_null($mid_boss_kill_rate)) {
            throw new \InvalidArgumentException('non-nullable mid_boss_kill_rate cannot be null');
        }
        $this->container['mid_boss_kill_rate'] = $mid_boss_kill_rate;

        return $this;
    }

    /**
     * Gets team0_wins
     *
     * @return int
     */
    public function getTeam0Wins()
    {
        return $this->container['team0_wins'];
    }

    /**
     * Sets team0_wins
     *
     * @param int $team0_wins team0_wins
     *
     * @return self
     */
    public function setTeam0Wins($team0_wins)
    {
        if (is_null($team0_wins)) {
            throw new \InvalidArgumentException('non-nullable team0_wins cannot be null');
        }
        if (($team0_wins < 0)) {
            throw new \InvalidArgumentException('invalid value for $team0_wins when calling AnalyticsGameStats., must be bigger than or equal to 0.');
        }

        $this->container['team0_wins'] = $team0_wins;

        return $this;
    }

    /**
     * Gets team1_wins
     *
     * @return int
     */
    public function getTeam1Wins()
    {
        return $this->container['team1_wins'];
    }

    /**
     * Sets team1_wins
     *
     * @param int $team1_wins team1_wins
     *
     * @return self
     */
    public function setTeam1Wins($team1_wins)
    {
        if (is_null($team1_wins)) {
            throw new \InvalidArgumentException('non-nullable team1_wins cannot be null');
        }
        if (($team1_wins < 0)) {
            throw new \InvalidArgumentException('invalid value for $team1_wins when calling AnalyticsGameStats., must be bigger than or equal to 0.');
        }

        $this->container['team1_wins'] = $team1_wins;

        return $this;
    }

    /**
     * Gets total_matches
     *
     * @return int
     */
    public function getTotalMatches()
    {
        return $this->container['total_matches'];
    }

    /**
     * Sets total_matches
     *
     * @param int $total_matches total_matches
     *
     * @return self
     */
    public function setTotalMatches($total_matches)
    {
        if (is_null($total_matches)) {
            throw new \InvalidArgumentException('non-nullable total_matches cannot be null');
        }
        if (($total_matches < 0)) {
            throw new \InvalidArgumentException('invalid value for $total_matches when calling AnalyticsGameStats., must be bigger than or equal to 0.');
        }

        $this->container['total_matches'] = $total_matches;

        return $this;
    }

    /**
     * Gets total_players
     *
     * @return int
     */
    public function getTotalPlayers()
    {
        return $this->container['total_players'];
    }

    /**
     * Sets total_players
     *
     * @param int $total_players total_players
     *
     * @return self
     */
    public function setTotalPlayers($total_players)
    {
        if (is_null($total_players)) {
            throw new \InvalidArgumentException('non-nullable total_players cannot be null');
        }
        if (($total_players < 0)) {
            throw new \InvalidArgumentException('invalid value for $total_players when calling AnalyticsGameStats., must be bigger than or equal to 0.');
        }

        $this->container['total_players'] = $total_players;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


