<?php
/**
 * GenericData
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Deadlock API
 *
 * ## API Clients  We have auto generated and updated clients for many languages. You can find them here: [https://github.com/deadlock-api/openapi-clients](https://github.com/deadlock-api/openapi-clients)  ## Support the Deadlock API  Whether you're building your own database, developing data science projects, or enhancing your website with game and player analytics, the Deadlock API has the data you need.  Your sponsorship helps keep this resource open, free and future-proof for everyone. By supporting the Deadlock API, you will enable continued development, new features and reliable access for developers, analysts and streamers worldwide.  Help us continue to provide the data you need - sponsor the Deadlock API today!  **-> You can Sponsor the Deadlock API on [Patreon](https://www.patreon.com/c/user?u=68961896) or [GitHub](https://github.com/sponsors/raimannma)**  ## Disclaimer _deadlock-api.com is not endorsed by Valve and does not reflect the views or opinions of Valve or anyone officially involved in producing or managing Valve properties. Valve and all associated properties are trademarks or registered trademarks of Valve Corporation_
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * GenericData Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class GenericData implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'GenericData';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'aim_spring_strength' => 'float[]',
        'armor_groups' => '\OpenAPI\Client\Model\ItemGroup[]',
        'damage_flash' => '\OpenAPI\Client\Model\DamageFlash',
        'enemy_objectives_and_zipline_color' => '\OpenAPI\Client\Model\Color',
        'enemy_objectives_color' => '\OpenAPI\Client\Model\Color',
        'enemy_zipline_color' => '\OpenAPI\Client\Model\Color',
        'glitch_settings' => '\OpenAPI\Client\Model\GlitchSettings',
        'hero_kill_gold_share_frac' => 'float[]',
        'item_price_per_tier' => 'int[]',
        'lane_info' => '\OpenAPI\Client\Model\LaneInfo[]',
        'mini_map_offsets' => '\OpenAPI\Client\Model\MiniMapOffsets[]',
        'minimap_team_combine_color' => '\OpenAPI\Client\Model\Color',
        'minimap_team_rebels_color' => '\OpenAPI\Client\Model\Color',
        'new_player_metrics' => '\OpenAPI\Client\Model\NewPlayerMetrics[]',
        'objective_params' => '\OpenAPI\Client\Model\ObjectiveParams',
        'rejuv_params' => '\OpenAPI\Client\Model\RejuvParams',
        'spirit_groups' => '\OpenAPI\Client\Model\ItemGroup[]',
        'street_brawl' => '\OpenAPI\Client\Model\StreetBrawl',
        'targeting_spring_strength' => 'float[]',
        'trooper_kill_gold_share_frac' => 'float[]',
        'weapon_groups' => '\OpenAPI\Client\Model\ItemGroup[]'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'aim_spring_strength' => 'double',
        'armor_groups' => null,
        'damage_flash' => null,
        'enemy_objectives_and_zipline_color' => null,
        'enemy_objectives_color' => null,
        'enemy_zipline_color' => null,
        'glitch_settings' => null,
        'hero_kill_gold_share_frac' => 'double',
        'item_price_per_tier' => 'int64',
        'lane_info' => null,
        'mini_map_offsets' => null,
        'minimap_team_combine_color' => null,
        'minimap_team_rebels_color' => null,
        'new_player_metrics' => null,
        'objective_params' => null,
        'rejuv_params' => null,
        'spirit_groups' => null,
        'street_brawl' => null,
        'targeting_spring_strength' => 'double',
        'trooper_kill_gold_share_frac' => 'double',
        'weapon_groups' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'aim_spring_strength' => false,
        'armor_groups' => false,
        'damage_flash' => false,
        'enemy_objectives_and_zipline_color' => true,
        'enemy_objectives_color' => true,
        'enemy_zipline_color' => true,
        'glitch_settings' => false,
        'hero_kill_gold_share_frac' => false,
        'item_price_per_tier' => false,
        'lane_info' => false,
        'mini_map_offsets' => false,
        'minimap_team_combine_color' => true,
        'minimap_team_rebels_color' => true,
        'new_player_metrics' => false,
        'objective_params' => false,
        'rejuv_params' => false,
        'spirit_groups' => false,
        'street_brawl' => true,
        'targeting_spring_strength' => false,
        'trooper_kill_gold_share_frac' => false,
        'weapon_groups' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'aim_spring_strength' => 'aim_spring_strength',
        'armor_groups' => 'armor_groups',
        'damage_flash' => 'damage_flash',
        'enemy_objectives_and_zipline_color' => 'enemy_objectives_and_zipline_color',
        'enemy_objectives_color' => 'enemy_objectives_color',
        'enemy_zipline_color' => 'enemy_zipline_color',
        'glitch_settings' => 'glitch_settings',
        'hero_kill_gold_share_frac' => 'hero_kill_gold_share_frac',
        'item_price_per_tier' => 'item_price_per_tier',
        'lane_info' => 'lane_info',
        'mini_map_offsets' => 'mini_map_offsets',
        'minimap_team_combine_color' => 'minimap_team_combine_color',
        'minimap_team_rebels_color' => 'minimap_team_rebels_color',
        'new_player_metrics' => 'new_player_metrics',
        'objective_params' => 'objective_params',
        'rejuv_params' => 'rejuv_params',
        'spirit_groups' => 'spirit_groups',
        'street_brawl' => 'street_brawl',
        'targeting_spring_strength' => 'targeting_spring_strength',
        'trooper_kill_gold_share_frac' => 'trooper_kill_gold_share_frac',
        'weapon_groups' => 'weapon_groups'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'aim_spring_strength' => 'setAimSpringStrength',
        'armor_groups' => 'setArmorGroups',
        'damage_flash' => 'setDamageFlash',
        'enemy_objectives_and_zipline_color' => 'setEnemyObjectivesAndZiplineColor',
        'enemy_objectives_color' => 'setEnemyObjectivesColor',
        'enemy_zipline_color' => 'setEnemyZiplineColor',
        'glitch_settings' => 'setGlitchSettings',
        'hero_kill_gold_share_frac' => 'setHeroKillGoldShareFrac',
        'item_price_per_tier' => 'setItemPricePerTier',
        'lane_info' => 'setLaneInfo',
        'mini_map_offsets' => 'setMiniMapOffsets',
        'minimap_team_combine_color' => 'setMinimapTeamCombineColor',
        'minimap_team_rebels_color' => 'setMinimapTeamRebelsColor',
        'new_player_metrics' => 'setNewPlayerMetrics',
        'objective_params' => 'setObjectiveParams',
        'rejuv_params' => 'setRejuvParams',
        'spirit_groups' => 'setSpiritGroups',
        'street_brawl' => 'setStreetBrawl',
        'targeting_spring_strength' => 'setTargetingSpringStrength',
        'trooper_kill_gold_share_frac' => 'setTrooperKillGoldShareFrac',
        'weapon_groups' => 'setWeaponGroups'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'aim_spring_strength' => 'getAimSpringStrength',
        'armor_groups' => 'getArmorGroups',
        'damage_flash' => 'getDamageFlash',
        'enemy_objectives_and_zipline_color' => 'getEnemyObjectivesAndZiplineColor',
        'enemy_objectives_color' => 'getEnemyObjectivesColor',
        'enemy_zipline_color' => 'getEnemyZiplineColor',
        'glitch_settings' => 'getGlitchSettings',
        'hero_kill_gold_share_frac' => 'getHeroKillGoldShareFrac',
        'item_price_per_tier' => 'getItemPricePerTier',
        'lane_info' => 'getLaneInfo',
        'mini_map_offsets' => 'getMiniMapOffsets',
        'minimap_team_combine_color' => 'getMinimapTeamCombineColor',
        'minimap_team_rebels_color' => 'getMinimapTeamRebelsColor',
        'new_player_metrics' => 'getNewPlayerMetrics',
        'objective_params' => 'getObjectiveParams',
        'rejuv_params' => 'getRejuvParams',
        'spirit_groups' => 'getSpiritGroups',
        'street_brawl' => 'getStreetBrawl',
        'targeting_spring_strength' => 'getTargetingSpringStrength',
        'trooper_kill_gold_share_frac' => 'getTrooperKillGoldShareFrac',
        'weapon_groups' => 'getWeaponGroups'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('aim_spring_strength', $data ?? [], null);
        $this->setIfExists('armor_groups', $data ?? [], null);
        $this->setIfExists('damage_flash', $data ?? [], null);
        $this->setIfExists('enemy_objectives_and_zipline_color', $data ?? [], null);
        $this->setIfExists('enemy_objectives_color', $data ?? [], null);
        $this->setIfExists('enemy_zipline_color', $data ?? [], null);
        $this->setIfExists('glitch_settings', $data ?? [], null);
        $this->setIfExists('hero_kill_gold_share_frac', $data ?? [], null);
        $this->setIfExists('item_price_per_tier', $data ?? [], null);
        $this->setIfExists('lane_info', $data ?? [], null);
        $this->setIfExists('mini_map_offsets', $data ?? [], null);
        $this->setIfExists('minimap_team_combine_color', $data ?? [], null);
        $this->setIfExists('minimap_team_rebels_color', $data ?? [], null);
        $this->setIfExists('new_player_metrics', $data ?? [], null);
        $this->setIfExists('objective_params', $data ?? [], null);
        $this->setIfExists('rejuv_params', $data ?? [], null);
        $this->setIfExists('spirit_groups', $data ?? [], null);
        $this->setIfExists('street_brawl', $data ?? [], null);
        $this->setIfExists('targeting_spring_strength', $data ?? [], null);
        $this->setIfExists('trooper_kill_gold_share_frac', $data ?? [], null);
        $this->setIfExists('weapon_groups', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['aim_spring_strength'] === null) {
            $invalidProperties[] = "'aim_spring_strength' can't be null";
        }
        if ($this->container['armor_groups'] === null) {
            $invalidProperties[] = "'armor_groups' can't be null";
        }
        if ($this->container['damage_flash'] === null) {
            $invalidProperties[] = "'damage_flash' can't be null";
        }
        if ($this->container['glitch_settings'] === null) {
            $invalidProperties[] = "'glitch_settings' can't be null";
        }
        if ($this->container['hero_kill_gold_share_frac'] === null) {
            $invalidProperties[] = "'hero_kill_gold_share_frac' can't be null";
        }
        if ($this->container['item_price_per_tier'] === null) {
            $invalidProperties[] = "'item_price_per_tier' can't be null";
        }
        if ($this->container['lane_info'] === null) {
            $invalidProperties[] = "'lane_info' can't be null";
        }
        if ($this->container['mini_map_offsets'] === null) {
            $invalidProperties[] = "'mini_map_offsets' can't be null";
        }
        if ($this->container['new_player_metrics'] === null) {
            $invalidProperties[] = "'new_player_metrics' can't be null";
        }
        if ($this->container['objective_params'] === null) {
            $invalidProperties[] = "'objective_params' can't be null";
        }
        if ($this->container['rejuv_params'] === null) {
            $invalidProperties[] = "'rejuv_params' can't be null";
        }
        if ($this->container['spirit_groups'] === null) {
            $invalidProperties[] = "'spirit_groups' can't be null";
        }
        if ($this->container['targeting_spring_strength'] === null) {
            $invalidProperties[] = "'targeting_spring_strength' can't be null";
        }
        if ($this->container['trooper_kill_gold_share_frac'] === null) {
            $invalidProperties[] = "'trooper_kill_gold_share_frac' can't be null";
        }
        if ($this->container['weapon_groups'] === null) {
            $invalidProperties[] = "'weapon_groups' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets aim_spring_strength
     *
     * @return float[]
     */
    public function getAimSpringStrength()
    {
        return $this->container['aim_spring_strength'];
    }

    /**
     * Sets aim_spring_strength
     *
     * @param float[] $aim_spring_strength aim_spring_strength
     *
     * @return self
     */
    public function setAimSpringStrength($aim_spring_strength)
    {
        if (is_null($aim_spring_strength)) {
            throw new \InvalidArgumentException('non-nullable aim_spring_strength cannot be null');
        }
        $this->container['aim_spring_strength'] = $aim_spring_strength;

        return $this;
    }

    /**
     * Gets armor_groups
     *
     * @return \OpenAPI\Client\Model\ItemGroup[]
     */
    public function getArmorGroups()
    {
        return $this->container['armor_groups'];
    }

    /**
     * Sets armor_groups
     *
     * @param \OpenAPI\Client\Model\ItemGroup[] $armor_groups armor_groups
     *
     * @return self
     */
    public function setArmorGroups($armor_groups)
    {
        if (is_null($armor_groups)) {
            throw new \InvalidArgumentException('non-nullable armor_groups cannot be null');
        }
        $this->container['armor_groups'] = $armor_groups;

        return $this;
    }

    /**
     * Gets damage_flash
     *
     * @return \OpenAPI\Client\Model\DamageFlash
     */
    public function getDamageFlash()
    {
        return $this->container['damage_flash'];
    }

    /**
     * Sets damage_flash
     *
     * @param \OpenAPI\Client\Model\DamageFlash $damage_flash damage_flash
     *
     * @return self
     */
    public function setDamageFlash($damage_flash)
    {
        if (is_null($damage_flash)) {
            throw new \InvalidArgumentException('non-nullable damage_flash cannot be null');
        }
        $this->container['damage_flash'] = $damage_flash;

        return $this;
    }

    /**
     * Gets enemy_objectives_and_zipline_color
     *
     * @return \OpenAPI\Client\Model\Color|null
     */
    public function getEnemyObjectivesAndZiplineColor()
    {
        return $this->container['enemy_objectives_and_zipline_color'];
    }

    /**
     * Sets enemy_objectives_and_zipline_color
     *
     * @param \OpenAPI\Client\Model\Color|null $enemy_objectives_and_zipline_color enemy_objectives_and_zipline_color
     *
     * @return self
     */
    public function setEnemyObjectivesAndZiplineColor($enemy_objectives_and_zipline_color)
    {
        if (is_null($enemy_objectives_and_zipline_color)) {
            array_push($this->openAPINullablesSetToNull, 'enemy_objectives_and_zipline_color');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('enemy_objectives_and_zipline_color', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['enemy_objectives_and_zipline_color'] = $enemy_objectives_and_zipline_color;

        return $this;
    }

    /**
     * Gets enemy_objectives_color
     *
     * @return \OpenAPI\Client\Model\Color|null
     */
    public function getEnemyObjectivesColor()
    {
        return $this->container['enemy_objectives_color'];
    }

    /**
     * Sets enemy_objectives_color
     *
     * @param \OpenAPI\Client\Model\Color|null $enemy_objectives_color enemy_objectives_color
     *
     * @return self
     */
    public function setEnemyObjectivesColor($enemy_objectives_color)
    {
        if (is_null($enemy_objectives_color)) {
            array_push($this->openAPINullablesSetToNull, 'enemy_objectives_color');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('enemy_objectives_color', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['enemy_objectives_color'] = $enemy_objectives_color;

        return $this;
    }

    /**
     * Gets enemy_zipline_color
     *
     * @return \OpenAPI\Client\Model\Color|null
     */
    public function getEnemyZiplineColor()
    {
        return $this->container['enemy_zipline_color'];
    }

    /**
     * Sets enemy_zipline_color
     *
     * @param \OpenAPI\Client\Model\Color|null $enemy_zipline_color enemy_zipline_color
     *
     * @return self
     */
    public function setEnemyZiplineColor($enemy_zipline_color)
    {
        if (is_null($enemy_zipline_color)) {
            array_push($this->openAPINullablesSetToNull, 'enemy_zipline_color');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('enemy_zipline_color', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['enemy_zipline_color'] = $enemy_zipline_color;

        return $this;
    }

    /**
     * Gets glitch_settings
     *
     * @return \OpenAPI\Client\Model\GlitchSettings
     */
    public function getGlitchSettings()
    {
        return $this->container['glitch_settings'];
    }

    /**
     * Sets glitch_settings
     *
     * @param \OpenAPI\Client\Model\GlitchSettings $glitch_settings glitch_settings
     *
     * @return self
     */
    public function setGlitchSettings($glitch_settings)
    {
        if (is_null($glitch_settings)) {
            throw new \InvalidArgumentException('non-nullable glitch_settings cannot be null');
        }
        $this->container['glitch_settings'] = $glitch_settings;

        return $this;
    }

    /**
     * Gets hero_kill_gold_share_frac
     *
     * @return float[]
     */
    public function getHeroKillGoldShareFrac()
    {
        return $this->container['hero_kill_gold_share_frac'];
    }

    /**
     * Sets hero_kill_gold_share_frac
     *
     * @param float[] $hero_kill_gold_share_frac hero_kill_gold_share_frac
     *
     * @return self
     */
    public function setHeroKillGoldShareFrac($hero_kill_gold_share_frac)
    {
        if (is_null($hero_kill_gold_share_frac)) {
            throw new \InvalidArgumentException('non-nullable hero_kill_gold_share_frac cannot be null');
        }
        $this->container['hero_kill_gold_share_frac'] = $hero_kill_gold_share_frac;

        return $this;
    }

    /**
     * Gets item_price_per_tier
     *
     * @return int[]
     */
    public function getItemPricePerTier()
    {
        return $this->container['item_price_per_tier'];
    }

    /**
     * Sets item_price_per_tier
     *
     * @param int[] $item_price_per_tier item_price_per_tier
     *
     * @return self
     */
    public function setItemPricePerTier($item_price_per_tier)
    {
        if (is_null($item_price_per_tier)) {
            throw new \InvalidArgumentException('non-nullable item_price_per_tier cannot be null');
        }
        $this->container['item_price_per_tier'] = $item_price_per_tier;

        return $this;
    }

    /**
     * Gets lane_info
     *
     * @return \OpenAPI\Client\Model\LaneInfo[]
     */
    public function getLaneInfo()
    {
        return $this->container['lane_info'];
    }

    /**
     * Sets lane_info
     *
     * @param \OpenAPI\Client\Model\LaneInfo[] $lane_info lane_info
     *
     * @return self
     */
    public function setLaneInfo($lane_info)
    {
        if (is_null($lane_info)) {
            throw new \InvalidArgumentException('non-nullable lane_info cannot be null');
        }
        $this->container['lane_info'] = $lane_info;

        return $this;
    }

    /**
     * Gets mini_map_offsets
     *
     * @return \OpenAPI\Client\Model\MiniMapOffsets[]
     */
    public function getMiniMapOffsets()
    {
        return $this->container['mini_map_offsets'];
    }

    /**
     * Sets mini_map_offsets
     *
     * @param \OpenAPI\Client\Model\MiniMapOffsets[] $mini_map_offsets mini_map_offsets
     *
     * @return self
     */
    public function setMiniMapOffsets($mini_map_offsets)
    {
        if (is_null($mini_map_offsets)) {
            throw new \InvalidArgumentException('non-nullable mini_map_offsets cannot be null');
        }
        $this->container['mini_map_offsets'] = $mini_map_offsets;

        return $this;
    }

    /**
     * Gets minimap_team_combine_color
     *
     * @return \OpenAPI\Client\Model\Color|null
     */
    public function getMinimapTeamCombineColor()
    {
        return $this->container['minimap_team_combine_color'];
    }

    /**
     * Sets minimap_team_combine_color
     *
     * @param \OpenAPI\Client\Model\Color|null $minimap_team_combine_color minimap_team_combine_color
     *
     * @return self
     */
    public function setMinimapTeamCombineColor($minimap_team_combine_color)
    {
        if (is_null($minimap_team_combine_color)) {
            array_push($this->openAPINullablesSetToNull, 'minimap_team_combine_color');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('minimap_team_combine_color', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['minimap_team_combine_color'] = $minimap_team_combine_color;

        return $this;
    }

    /**
     * Gets minimap_team_rebels_color
     *
     * @return \OpenAPI\Client\Model\Color|null
     */
    public function getMinimapTeamRebelsColor()
    {
        return $this->container['minimap_team_rebels_color'];
    }

    /**
     * Sets minimap_team_rebels_color
     *
     * @param \OpenAPI\Client\Model\Color|null $minimap_team_rebels_color minimap_team_rebels_color
     *
     * @return self
     */
    public function setMinimapTeamRebelsColor($minimap_team_rebels_color)
    {
        if (is_null($minimap_team_rebels_color)) {
            array_push($this->openAPINullablesSetToNull, 'minimap_team_rebels_color');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('minimap_team_rebels_color', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['minimap_team_rebels_color'] = $minimap_team_rebels_color;

        return $this;
    }

    /**
     * Gets new_player_metrics
     *
     * @return \OpenAPI\Client\Model\NewPlayerMetrics[]
     */
    public function getNewPlayerMetrics()
    {
        return $this->container['new_player_metrics'];
    }

    /**
     * Sets new_player_metrics
     *
     * @param \OpenAPI\Client\Model\NewPlayerMetrics[] $new_player_metrics new_player_metrics
     *
     * @return self
     */
    public function setNewPlayerMetrics($new_player_metrics)
    {
        if (is_null($new_player_metrics)) {
            throw new \InvalidArgumentException('non-nullable new_player_metrics cannot be null');
        }
        $this->container['new_player_metrics'] = $new_player_metrics;

        return $this;
    }

    /**
     * Gets objective_params
     *
     * @return \OpenAPI\Client\Model\ObjectiveParams
     */
    public function getObjectiveParams()
    {
        return $this->container['objective_params'];
    }

    /**
     * Sets objective_params
     *
     * @param \OpenAPI\Client\Model\ObjectiveParams $objective_params objective_params
     *
     * @return self
     */
    public function setObjectiveParams($objective_params)
    {
        if (is_null($objective_params)) {
            throw new \InvalidArgumentException('non-nullable objective_params cannot be null');
        }
        $this->container['objective_params'] = $objective_params;

        return $this;
    }

    /**
     * Gets rejuv_params
     *
     * @return \OpenAPI\Client\Model\RejuvParams
     */
    public function getRejuvParams()
    {
        return $this->container['rejuv_params'];
    }

    /**
     * Sets rejuv_params
     *
     * @param \OpenAPI\Client\Model\RejuvParams $rejuv_params rejuv_params
     *
     * @return self
     */
    public function setRejuvParams($rejuv_params)
    {
        if (is_null($rejuv_params)) {
            throw new \InvalidArgumentException('non-nullable rejuv_params cannot be null');
        }
        $this->container['rejuv_params'] = $rejuv_params;

        return $this;
    }

    /**
     * Gets spirit_groups
     *
     * @return \OpenAPI\Client\Model\ItemGroup[]
     */
    public function getSpiritGroups()
    {
        return $this->container['spirit_groups'];
    }

    /**
     * Sets spirit_groups
     *
     * @param \OpenAPI\Client\Model\ItemGroup[] $spirit_groups spirit_groups
     *
     * @return self
     */
    public function setSpiritGroups($spirit_groups)
    {
        if (is_null($spirit_groups)) {
            throw new \InvalidArgumentException('non-nullable spirit_groups cannot be null');
        }
        $this->container['spirit_groups'] = $spirit_groups;

        return $this;
    }

    /**
     * Gets street_brawl
     *
     * @return \OpenAPI\Client\Model\StreetBrawl|null
     */
    public function getStreetBrawl()
    {
        return $this->container['street_brawl'];
    }

    /**
     * Sets street_brawl
     *
     * @param \OpenAPI\Client\Model\StreetBrawl|null $street_brawl street_brawl
     *
     * @return self
     */
    public function setStreetBrawl($street_brawl)
    {
        if (is_null($street_brawl)) {
            array_push($this->openAPINullablesSetToNull, 'street_brawl');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('street_brawl', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['street_brawl'] = $street_brawl;

        return $this;
    }

    /**
     * Gets targeting_spring_strength
     *
     * @return float[]
     */
    public function getTargetingSpringStrength()
    {
        return $this->container['targeting_spring_strength'];
    }

    /**
     * Sets targeting_spring_strength
     *
     * @param float[] $targeting_spring_strength targeting_spring_strength
     *
     * @return self
     */
    public function setTargetingSpringStrength($targeting_spring_strength)
    {
        if (is_null($targeting_spring_strength)) {
            throw new \InvalidArgumentException('non-nullable targeting_spring_strength cannot be null');
        }
        $this->container['targeting_spring_strength'] = $targeting_spring_strength;

        return $this;
    }

    /**
     * Gets trooper_kill_gold_share_frac
     *
     * @return float[]
     */
    public function getTrooperKillGoldShareFrac()
    {
        return $this->container['trooper_kill_gold_share_frac'];
    }

    /**
     * Sets trooper_kill_gold_share_frac
     *
     * @param float[] $trooper_kill_gold_share_frac trooper_kill_gold_share_frac
     *
     * @return self
     */
    public function setTrooperKillGoldShareFrac($trooper_kill_gold_share_frac)
    {
        if (is_null($trooper_kill_gold_share_frac)) {
            throw new \InvalidArgumentException('non-nullable trooper_kill_gold_share_frac cannot be null');
        }
        $this->container['trooper_kill_gold_share_frac'] = $trooper_kill_gold_share_frac;

        return $this;
    }

    /**
     * Gets weapon_groups
     *
     * @return \OpenAPI\Client\Model\ItemGroup[]
     */
    public function getWeaponGroups()
    {
        return $this->container['weapon_groups'];
    }

    /**
     * Sets weapon_groups
     *
     * @param \OpenAPI\Client\Model\ItemGroup[] $weapon_groups weapon_groups
     *
     * @return self
     */
    public function setWeaponGroups($weapon_groups)
    {
        if (is_null($weapon_groups)) {
            throw new \InvalidArgumentException('non-nullable weapon_groups cannot be null');
        }
        $this->container['weapon_groups'] = $weapon_groups;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


