<?php
/**
 * HeroBuildStats
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Deadlock API
 *
 * ## API Clients  We have auto generated and updated clients for many languages. You can find them here: [https://github.com/deadlock-api/openapi-clients](https://github.com/deadlock-api/openapi-clients)  ## Support the Deadlock API  Whether you're building your own database, developing data science projects, or enhancing your website with game and player analytics, the Deadlock API has the data you need.  Your sponsorship helps keep this resource open, free and future-proof for everyone. By supporting the Deadlock API, you will enable continued development, new features and reliable access for developers, analysts and streamers worldwide.  Help us continue to provide the data you need - sponsor the Deadlock API today!  **-> You can Sponsor the Deadlock API on [Patreon](https://www.patreon.com/c/user?u=68961896) or [GitHub](https://github.com/sponsors/raimannma)**  ## Disclaimer _deadlock-api.com is not endorsed by Valve and does not reflect the views or opinions of Valve or anyone officially involved in producing or managing Valve properties. Valve and all associated properties are trademarks or registered trademarks of Valve Corporation_
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * HeroBuildStats Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class HeroBuildStats implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'HeroBuildStats';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'hero_build_id' => 'int',
        'hero_id' => 'int',
        'losses' => 'int',
        'matches' => 'int',
        'players' => 'int',
        'wins' => 'int'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'hero_build_id' => 'int64',
        'hero_id' => 'int32',
        'losses' => 'int64',
        'matches' => 'int64',
        'players' => 'int64',
        'wins' => 'int64'
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'hero_build_id' => false,
        'hero_id' => false,
        'losses' => false,
        'matches' => false,
        'players' => false,
        'wins' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'hero_build_id' => 'hero_build_id',
        'hero_id' => 'hero_id',
        'losses' => 'losses',
        'matches' => 'matches',
        'players' => 'players',
        'wins' => 'wins'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'hero_build_id' => 'setHeroBuildId',
        'hero_id' => 'setHeroId',
        'losses' => 'setLosses',
        'matches' => 'setMatches',
        'players' => 'setPlayers',
        'wins' => 'setWins'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'hero_build_id' => 'getHeroBuildId',
        'hero_id' => 'getHeroId',
        'losses' => 'getLosses',
        'matches' => 'getMatches',
        'players' => 'getPlayers',
        'wins' => 'getWins'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('hero_build_id', $data ?? [], null);
        $this->setIfExists('hero_id', $data ?? [], null);
        $this->setIfExists('losses', $data ?? [], null);
        $this->setIfExists('matches', $data ?? [], null);
        $this->setIfExists('players', $data ?? [], null);
        $this->setIfExists('wins', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['hero_build_id'] === null) {
            $invalidProperties[] = "'hero_build_id' can't be null";
        }
        if (($this->container['hero_build_id'] < 0)) {
            $invalidProperties[] = "invalid value for 'hero_build_id', must be bigger than or equal to 0.";
        }

        if ($this->container['hero_id'] === null) {
            $invalidProperties[] = "'hero_id' can't be null";
        }
        if (($this->container['hero_id'] < 0)) {
            $invalidProperties[] = "invalid value for 'hero_id', must be bigger than or equal to 0.";
        }

        if ($this->container['losses'] === null) {
            $invalidProperties[] = "'losses' can't be null";
        }
        if (($this->container['losses'] < 0)) {
            $invalidProperties[] = "invalid value for 'losses', must be bigger than or equal to 0.";
        }

        if ($this->container['matches'] === null) {
            $invalidProperties[] = "'matches' can't be null";
        }
        if (($this->container['matches'] < 0)) {
            $invalidProperties[] = "invalid value for 'matches', must be bigger than or equal to 0.";
        }

        if ($this->container['players'] === null) {
            $invalidProperties[] = "'players' can't be null";
        }
        if (($this->container['players'] < 0)) {
            $invalidProperties[] = "invalid value for 'players', must be bigger than or equal to 0.";
        }

        if ($this->container['wins'] === null) {
            $invalidProperties[] = "'wins' can't be null";
        }
        if (($this->container['wins'] < 0)) {
            $invalidProperties[] = "invalid value for 'wins', must be bigger than or equal to 0.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets hero_build_id
     *
     * @return int
     */
    public function getHeroBuildId()
    {
        return $this->container['hero_build_id'];
    }

    /**
     * Sets hero_build_id
     *
     * @param int $hero_build_id The ID of the hero build. The `hero_build_id` is the first build the player had selected when the game started.
     *
     * @return self
     */
    public function setHeroBuildId($hero_build_id)
    {
        if (is_null($hero_build_id)) {
            throw new \InvalidArgumentException('non-nullable hero_build_id cannot be null');
        }
        if (($hero_build_id < 0)) {
            throw new \InvalidArgumentException('invalid value for $hero_build_id when calling HeroBuildStats., must be bigger than or equal to 0.');
        }

        $this->container['hero_build_id'] = $hero_build_id;

        return $this;
    }

    /**
     * Gets hero_id
     *
     * @return int
     */
    public function getHeroId()
    {
        return $this->container['hero_id'];
    }

    /**
     * Sets hero_id
     *
     * @param int $hero_id The ID of the hero. See more: <https://api.deadlock-api.com/v1/assets/heroes>
     *
     * @return self
     */
    public function setHeroId($hero_id)
    {
        if (is_null($hero_id)) {
            throw new \InvalidArgumentException('non-nullable hero_id cannot be null');
        }
        if (($hero_id < 0)) {
            throw new \InvalidArgumentException('invalid value for $hero_id when calling HeroBuildStats., must be bigger than or equal to 0.');
        }

        $this->container['hero_id'] = $hero_id;

        return $this;
    }

    /**
     * Gets losses
     *
     * @return int
     */
    public function getLosses()
    {
        return $this->container['losses'];
    }

    /**
     * Sets losses
     *
     * @param int $losses The number of losses with this build.
     *
     * @return self
     */
    public function setLosses($losses)
    {
        if (is_null($losses)) {
            throw new \InvalidArgumentException('non-nullable losses cannot be null');
        }
        if (($losses < 0)) {
            throw new \InvalidArgumentException('invalid value for $losses when calling HeroBuildStats., must be bigger than or equal to 0.');
        }

        $this->container['losses'] = $losses;

        return $this;
    }

    /**
     * Gets matches
     *
     * @return int
     */
    public function getMatches()
    {
        return $this->container['matches'];
    }

    /**
     * Sets matches
     *
     * @param int $matches The total number of matches played with this build (`wins + losses`).
     *
     * @return self
     */
    public function setMatches($matches)
    {
        if (is_null($matches)) {
            throw new \InvalidArgumentException('non-nullable matches cannot be null');
        }
        if (($matches < 0)) {
            throw new \InvalidArgumentException('invalid value for $matches when calling HeroBuildStats., must be bigger than or equal to 0.');
        }

        $this->container['matches'] = $matches;

        return $this;
    }

    /**
     * Gets players
     *
     * @return int
     */
    public function getPlayers()
    {
        return $this->container['players'];
    }

    /**
     * Sets players
     *
     * @param int $players The number of unique players who used this build.
     *
     * @return self
     */
    public function setPlayers($players)
    {
        if (is_null($players)) {
            throw new \InvalidArgumentException('non-nullable players cannot be null');
        }
        if (($players < 0)) {
            throw new \InvalidArgumentException('invalid value for $players when calling HeroBuildStats., must be bigger than or equal to 0.');
        }

        $this->container['players'] = $players;

        return $this;
    }

    /**
     * Gets wins
     *
     * @return int
     */
    public function getWins()
    {
        return $this->container['wins'];
    }

    /**
     * Sets wins
     *
     * @param int $wins The number of wins with this build.
     *
     * @return self
     */
    public function setWins($wins)
    {
        if (is_null($wins)) {
            throw new \InvalidArgumentException('non-nullable wins cannot be null');
        }
        if (($wins < 0)) {
            throw new \InvalidArgumentException('invalid value for $wins when calling HeroBuildStats., must be bigger than or equal to 0.');
        }

        $this->container['wins'] = $wins;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


