<?php
/**
 * RankedSeason
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Deadlock API
 *
 * ## API Clients  We have auto generated and updated clients for many languages. You can find them here: [https://github.com/deadlock-api/openapi-clients](https://github.com/deadlock-api/openapi-clients)  ## Support the Deadlock API  Whether you're building your own database, developing data science projects, or enhancing your website with game and player analytics, the Deadlock API has the data you need.  Your sponsorship helps keep this resource open, free and future-proof for everyone. By supporting the Deadlock API, you will enable continued development, new features and reliable access for developers, analysts and streamers worldwide.  Help us continue to provide the data you need - sponsor the Deadlock API today!  **-> You can Sponsor the Deadlock API on [Patreon](https://www.patreon.com/c/user?u=68961896) or [GitHub](https://github.com/sponsors/raimannma)**  ## Disclaimer _deadlock-api.com is not endorsed by Valve and does not reflect the views or opinions of Valve or anyone officially involved in producing or managing Valve properties. Valve and all associated properties are trademarks or registered trademarks of Valve Corporation_
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * RankedSeason Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class RankedSeason implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'RankedSeason';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'calibration_matches' => 'int',
        'class_name' => 'string',
        'intervals' => '\OpenAPI\Client\Model\SeasonInterval[]',
        'min_hero_unlocks' => 'int',
        'min_hero_wins' => 'int',
        'min_wins' => 'int',
        'name' => 'string',
        'ranked_type' => 'string',
        'valid_party_sizes' => 'int[]'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'calibration_matches' => 'int32',
        'class_name' => null,
        'intervals' => null,
        'min_hero_unlocks' => 'int32',
        'min_hero_wins' => 'int32',
        'min_wins' => 'int32',
        'name' => null,
        'ranked_type' => null,
        'valid_party_sizes' => 'int32'
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'calibration_matches' => false,
        'class_name' => false,
        'intervals' => false,
        'min_hero_unlocks' => false,
        'min_hero_wins' => false,
        'min_wins' => false,
        'name' => false,
        'ranked_type' => false,
        'valid_party_sizes' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'calibration_matches' => 'calibration_matches',
        'class_name' => 'class_name',
        'intervals' => 'intervals',
        'min_hero_unlocks' => 'min_hero_unlocks',
        'min_hero_wins' => 'min_hero_wins',
        'min_wins' => 'min_wins',
        'name' => 'name',
        'ranked_type' => 'ranked_type',
        'valid_party_sizes' => 'valid_party_sizes'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'calibration_matches' => 'setCalibrationMatches',
        'class_name' => 'setClassName',
        'intervals' => 'setIntervals',
        'min_hero_unlocks' => 'setMinHeroUnlocks',
        'min_hero_wins' => 'setMinHeroWins',
        'min_wins' => 'setMinWins',
        'name' => 'setName',
        'ranked_type' => 'setRankedType',
        'valid_party_sizes' => 'setValidPartySizes'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'calibration_matches' => 'getCalibrationMatches',
        'class_name' => 'getClassName',
        'intervals' => 'getIntervals',
        'min_hero_unlocks' => 'getMinHeroUnlocks',
        'min_hero_wins' => 'getMinHeroWins',
        'min_wins' => 'getMinWins',
        'name' => 'getName',
        'ranked_type' => 'getRankedType',
        'valid_party_sizes' => 'getValidPartySizes'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('calibration_matches', $data ?? [], null);
        $this->setIfExists('class_name', $data ?? [], null);
        $this->setIfExists('intervals', $data ?? [], null);
        $this->setIfExists('min_hero_unlocks', $data ?? [], null);
        $this->setIfExists('min_hero_wins', $data ?? [], null);
        $this->setIfExists('min_wins', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('ranked_type', $data ?? [], null);
        $this->setIfExists('valid_party_sizes', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['calibration_matches'] === null) {
            $invalidProperties[] = "'calibration_matches' can't be null";
        }
        if (($this->container['calibration_matches'] < 0)) {
            $invalidProperties[] = "invalid value for 'calibration_matches', must be bigger than or equal to 0.";
        }

        if ($this->container['class_name'] === null) {
            $invalidProperties[] = "'class_name' can't be null";
        }
        if ($this->container['intervals'] === null) {
            $invalidProperties[] = "'intervals' can't be null";
        }
        if ($this->container['min_hero_unlocks'] === null) {
            $invalidProperties[] = "'min_hero_unlocks' can't be null";
        }
        if (($this->container['min_hero_unlocks'] < 0)) {
            $invalidProperties[] = "invalid value for 'min_hero_unlocks', must be bigger than or equal to 0.";
        }

        if ($this->container['min_hero_wins'] === null) {
            $invalidProperties[] = "'min_hero_wins' can't be null";
        }
        if (($this->container['min_hero_wins'] < 0)) {
            $invalidProperties[] = "invalid value for 'min_hero_wins', must be bigger than or equal to 0.";
        }

        if ($this->container['min_wins'] === null) {
            $invalidProperties[] = "'min_wins' can't be null";
        }
        if (($this->container['min_wins'] < 0)) {
            $invalidProperties[] = "invalid value for 'min_wins', must be bigger than or equal to 0.";
        }

        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['ranked_type'] === null) {
            $invalidProperties[] = "'ranked_type' can't be null";
        }
        if ($this->container['valid_party_sizes'] === null) {
            $invalidProperties[] = "'valid_party_sizes' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets calibration_matches
     *
     * @return int
     */
    public function getCalibrationMatches()
    {
        return $this->container['calibration_matches'];
    }

    /**
     * Sets calibration_matches
     *
     * @param int $calibration_matches calibration_matches
     *
     * @return self
     */
    public function setCalibrationMatches($calibration_matches)
    {
        if (is_null($calibration_matches)) {
            throw new \InvalidArgumentException('non-nullable calibration_matches cannot be null');
        }
        if (($calibration_matches < 0)) {
            throw new \InvalidArgumentException('invalid value for $calibration_matches when calling RankedSeason., must be bigger than or equal to 0.');
        }

        $this->container['calibration_matches'] = $calibration_matches;

        return $this;
    }

    /**
     * Gets class_name
     *
     * @return string
     */
    public function getClassName()
    {
        return $this->container['class_name'];
    }

    /**
     * Sets class_name
     *
     * @param string $class_name class_name
     *
     * @return self
     */
    public function setClassName($class_name)
    {
        if (is_null($class_name)) {
            throw new \InvalidArgumentException('non-nullable class_name cannot be null');
        }
        $this->container['class_name'] = $class_name;

        return $this;
    }

    /**
     * Gets intervals
     *
     * @return \OpenAPI\Client\Model\SeasonInterval[]
     */
    public function getIntervals()
    {
        return $this->container['intervals'];
    }

    /**
     * Sets intervals
     *
     * @param \OpenAPI\Client\Model\SeasonInterval[] $intervals intervals
     *
     * @return self
     */
    public function setIntervals($intervals)
    {
        if (is_null($intervals)) {
            throw new \InvalidArgumentException('non-nullable intervals cannot be null');
        }
        $this->container['intervals'] = $intervals;

        return $this;
    }

    /**
     * Gets min_hero_unlocks
     *
     * @return int
     */
    public function getMinHeroUnlocks()
    {
        return $this->container['min_hero_unlocks'];
    }

    /**
     * Sets min_hero_unlocks
     *
     * @param int $min_hero_unlocks min_hero_unlocks
     *
     * @return self
     */
    public function setMinHeroUnlocks($min_hero_unlocks)
    {
        if (is_null($min_hero_unlocks)) {
            throw new \InvalidArgumentException('non-nullable min_hero_unlocks cannot be null');
        }
        if (($min_hero_unlocks < 0)) {
            throw new \InvalidArgumentException('invalid value for $min_hero_unlocks when calling RankedSeason., must be bigger than or equal to 0.');
        }

        $this->container['min_hero_unlocks'] = $min_hero_unlocks;

        return $this;
    }

    /**
     * Gets min_hero_wins
     *
     * @return int
     */
    public function getMinHeroWins()
    {
        return $this->container['min_hero_wins'];
    }

    /**
     * Sets min_hero_wins
     *
     * @param int $min_hero_wins min_hero_wins
     *
     * @return self
     */
    public function setMinHeroWins($min_hero_wins)
    {
        if (is_null($min_hero_wins)) {
            throw new \InvalidArgumentException('non-nullable min_hero_wins cannot be null');
        }
        if (($min_hero_wins < 0)) {
            throw new \InvalidArgumentException('invalid value for $min_hero_wins when calling RankedSeason., must be bigger than or equal to 0.');
        }

        $this->container['min_hero_wins'] = $min_hero_wins;

        return $this;
    }

    /**
     * Gets min_wins
     *
     * @return int
     */
    public function getMinWins()
    {
        return $this->container['min_wins'];
    }

    /**
     * Sets min_wins
     *
     * @param int $min_wins min_wins
     *
     * @return self
     */
    public function setMinWins($min_wins)
    {
        if (is_null($min_wins)) {
            throw new \InvalidArgumentException('non-nullable min_wins cannot be null');
        }
        if (($min_wins < 0)) {
            throw new \InvalidArgumentException('invalid value for $min_wins when calling RankedSeason., must be bigger than or equal to 0.');
        }

        $this->container['min_wins'] = $min_wins;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets ranked_type
     *
     * @return string
     */
    public function getRankedType()
    {
        return $this->container['ranked_type'];
    }

    /**
     * Sets ranked_type
     *
     * @param string $ranked_type ranked_type
     *
     * @return self
     */
    public function setRankedType($ranked_type)
    {
        if (is_null($ranked_type)) {
            throw new \InvalidArgumentException('non-nullable ranked_type cannot be null');
        }
        $this->container['ranked_type'] = $ranked_type;

        return $this;
    }

    /**
     * Gets valid_party_sizes
     *
     * @return int[]
     */
    public function getValidPartySizes()
    {
        return $this->container['valid_party_sizes'];
    }

    /**
     * Sets valid_party_sizes
     *
     * @param int[] $valid_party_sizes valid_party_sizes
     *
     * @return self
     */
    public function setValidPartySizes($valid_party_sizes)
    {
        if (is_null($valid_party_sizes)) {
            throw new \InvalidArgumentException('non-nullable valid_party_sizes cannot be null');
        }
        $this->container['valid_party_sizes'] = $valid_party_sizes;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


