<?php
/**
 * SteamServer
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Deadlock API
 *
 * ## API Clients  We have auto generated and updated clients for many languages. You can find them here: [https://github.com/deadlock-api/openapi-clients](https://github.com/deadlock-api/openapi-clients)  ## Support the Deadlock API  Whether you're building your own database, developing data science projects, or enhancing your website with game and player analytics, the Deadlock API has the data you need.  Your sponsorship helps keep this resource open, free and future-proof for everyone. By supporting the Deadlock API, you will enable continued development, new features and reliable access for developers, analysts and streamers worldwide.  Help us continue to provide the data you need - sponsor the Deadlock API today!  **-> You can Sponsor the Deadlock API on [Patreon](https://www.patreon.com/c/user?u=68961896) or [GitHub](https://github.com/sponsors/raimannma)**  ## Disclaimer _deadlock-api.com is not endorsed by Valve and does not reflect the views or opinions of Valve or anyone officially involved in producing or managing Valve properties. Valve and all associated properties are trademarks or registered trademarks of Valve Corporation_
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * SteamServer Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class SteamServer implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'SteamServer';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'addr' => 'string',
        'appid' => 'int',
        'bots' => 'int',
        'dedicated' => 'bool',
        'gamedir' => 'string',
        'gameport' => 'int',
        'gametype' => 'string',
        'map' => 'string',
        'max_players' => 'int',
        'name' => 'string',
        'os' => 'string',
        'players' => 'int',
        'product' => 'string',
        'region' => 'int',
        'secure' => 'bool',
        'steamid' => 'string',
        'version' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'addr' => null,
        'appid' => 'int32',
        'bots' => 'int32',
        'dedicated' => null,
        'gamedir' => null,
        'gameport' => 'int32',
        'gametype' => null,
        'map' => null,
        'max_players' => 'int32',
        'name' => null,
        'os' => null,
        'players' => 'int32',
        'product' => null,
        'region' => 'int32',
        'secure' => null,
        'steamid' => null,
        'version' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'addr' => false,
        'appid' => false,
        'bots' => false,
        'dedicated' => false,
        'gamedir' => false,
        'gameport' => false,
        'gametype' => false,
        'map' => false,
        'max_players' => false,
        'name' => false,
        'os' => false,
        'players' => false,
        'product' => false,
        'region' => false,
        'secure' => false,
        'steamid' => false,
        'version' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'addr' => 'addr',
        'appid' => 'appid',
        'bots' => 'bots',
        'dedicated' => 'dedicated',
        'gamedir' => 'gamedir',
        'gameport' => 'gameport',
        'gametype' => 'gametype',
        'map' => 'map',
        'max_players' => 'max_players',
        'name' => 'name',
        'os' => 'os',
        'players' => 'players',
        'product' => 'product',
        'region' => 'region',
        'secure' => 'secure',
        'steamid' => 'steamid',
        'version' => 'version'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'addr' => 'setAddr',
        'appid' => 'setAppid',
        'bots' => 'setBots',
        'dedicated' => 'setDedicated',
        'gamedir' => 'setGamedir',
        'gameport' => 'setGameport',
        'gametype' => 'setGametype',
        'map' => 'setMap',
        'max_players' => 'setMaxPlayers',
        'name' => 'setName',
        'os' => 'setOs',
        'players' => 'setPlayers',
        'product' => 'setProduct',
        'region' => 'setRegion',
        'secure' => 'setSecure',
        'steamid' => 'setSteamid',
        'version' => 'setVersion'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'addr' => 'getAddr',
        'appid' => 'getAppid',
        'bots' => 'getBots',
        'dedicated' => 'getDedicated',
        'gamedir' => 'getGamedir',
        'gameport' => 'getGameport',
        'gametype' => 'getGametype',
        'map' => 'getMap',
        'max_players' => 'getMaxPlayers',
        'name' => 'getName',
        'os' => 'getOs',
        'players' => 'getPlayers',
        'product' => 'getProduct',
        'region' => 'getRegion',
        'secure' => 'getSecure',
        'steamid' => 'getSteamid',
        'version' => 'getVersion'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('addr', $data ?? [], null);
        $this->setIfExists('appid', $data ?? [], null);
        $this->setIfExists('bots', $data ?? [], null);
        $this->setIfExists('dedicated', $data ?? [], null);
        $this->setIfExists('gamedir', $data ?? [], null);
        $this->setIfExists('gameport', $data ?? [], null);
        $this->setIfExists('gametype', $data ?? [], null);
        $this->setIfExists('map', $data ?? [], null);
        $this->setIfExists('max_players', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('os', $data ?? [], null);
        $this->setIfExists('players', $data ?? [], null);
        $this->setIfExists('product', $data ?? [], null);
        $this->setIfExists('region', $data ?? [], null);
        $this->setIfExists('secure', $data ?? [], null);
        $this->setIfExists('steamid', $data ?? [], null);
        $this->setIfExists('version', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['addr'] === null) {
            $invalidProperties[] = "'addr' can't be null";
        }
        if ($this->container['appid'] === null) {
            $invalidProperties[] = "'appid' can't be null";
        }
        if (($this->container['appid'] < 0)) {
            $invalidProperties[] = "invalid value for 'appid', must be bigger than or equal to 0.";
        }

        if ($this->container['bots'] === null) {
            $invalidProperties[] = "'bots' can't be null";
        }
        if (($this->container['bots'] < 0)) {
            $invalidProperties[] = "invalid value for 'bots', must be bigger than or equal to 0.";
        }

        if ($this->container['dedicated'] === null) {
            $invalidProperties[] = "'dedicated' can't be null";
        }
        if ($this->container['gamedir'] === null) {
            $invalidProperties[] = "'gamedir' can't be null";
        }
        if ($this->container['gameport'] === null) {
            $invalidProperties[] = "'gameport' can't be null";
        }
        if (($this->container['gameport'] < 0)) {
            $invalidProperties[] = "invalid value for 'gameport', must be bigger than or equal to 0.";
        }

        if ($this->container['gametype'] === null) {
            $invalidProperties[] = "'gametype' can't be null";
        }
        if ($this->container['map'] === null) {
            $invalidProperties[] = "'map' can't be null";
        }
        if ($this->container['max_players'] === null) {
            $invalidProperties[] = "'max_players' can't be null";
        }
        if (($this->container['max_players'] < 0)) {
            $invalidProperties[] = "invalid value for 'max_players', must be bigger than or equal to 0.";
        }

        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['os'] === null) {
            $invalidProperties[] = "'os' can't be null";
        }
        if ($this->container['players'] === null) {
            $invalidProperties[] = "'players' can't be null";
        }
        if (($this->container['players'] < 0)) {
            $invalidProperties[] = "invalid value for 'players', must be bigger than or equal to 0.";
        }

        if ($this->container['product'] === null) {
            $invalidProperties[] = "'product' can't be null";
        }
        if ($this->container['region'] === null) {
            $invalidProperties[] = "'region' can't be null";
        }
        if ($this->container['secure'] === null) {
            $invalidProperties[] = "'secure' can't be null";
        }
        if ($this->container['steamid'] === null) {
            $invalidProperties[] = "'steamid' can't be null";
        }
        if ($this->container['version'] === null) {
            $invalidProperties[] = "'version' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets addr
     *
     * @return string
     */
    public function getAddr()
    {
        return $this->container['addr'];
    }

    /**
     * Sets addr
     *
     * @param string $addr Full address of the server including port (e.g. `1.2.3.4:27015`)
     *
     * @return self
     */
    public function setAddr($addr)
    {
        if (is_null($addr)) {
            throw new \InvalidArgumentException('non-nullable addr cannot be null');
        }
        $this->container['addr'] = $addr;

        return $this;
    }

    /**
     * Gets appid
     *
     * @return int
     */
    public function getAppid()
    {
        return $this->container['appid'];
    }

    /**
     * Sets appid
     *
     * @param int $appid Steam appid of the game running on this server
     *
     * @return self
     */
    public function setAppid($appid)
    {
        if (is_null($appid)) {
            throw new \InvalidArgumentException('non-nullable appid cannot be null');
        }
        if (($appid < 0)) {
            throw new \InvalidArgumentException('invalid value for $appid when calling SteamServer., must be bigger than or equal to 0.');
        }

        $this->container['appid'] = $appid;

        return $this;
    }

    /**
     * Gets bots
     *
     * @return int
     */
    public function getBots()
    {
        return $this->container['bots'];
    }

    /**
     * Sets bots
     *
     * @param int $bots Number of bots on the server
     *
     * @return self
     */
    public function setBots($bots)
    {
        if (is_null($bots)) {
            throw new \InvalidArgumentException('non-nullable bots cannot be null');
        }
        if (($bots < 0)) {
            throw new \InvalidArgumentException('invalid value for $bots when calling SteamServer., must be bigger than or equal to 0.');
        }

        $this->container['bots'] = $bots;

        return $this;
    }

    /**
     * Gets dedicated
     *
     * @return bool
     */
    public function getDedicated()
    {
        return $this->container['dedicated'];
    }

    /**
     * Sets dedicated
     *
     * @param bool $dedicated Whether this is a dedicated server
     *
     * @return self
     */
    public function setDedicated($dedicated)
    {
        if (is_null($dedicated)) {
            throw new \InvalidArgumentException('non-nullable dedicated cannot be null');
        }
        $this->container['dedicated'] = $dedicated;

        return $this;
    }

    /**
     * Gets gamedir
     *
     * @return string
     */
    public function getGamedir()
    {
        return $this->container['gamedir'];
    }

    /**
     * Sets gamedir
     *
     * @param string $gamedir Internal game directory name
     *
     * @return self
     */
    public function setGamedir($gamedir)
    {
        if (is_null($gamedir)) {
            throw new \InvalidArgumentException('non-nullable gamedir cannot be null');
        }
        $this->container['gamedir'] = $gamedir;

        return $this;
    }

    /**
     * Gets gameport
     *
     * @return int
     */
    public function getGameport()
    {
        return $this->container['gameport'];
    }

    /**
     * Sets gameport
     *
     * @param int $gameport Game port the server is listening on
     *
     * @return self
     */
    public function setGameport($gameport)
    {
        if (is_null($gameport)) {
            throw new \InvalidArgumentException('non-nullable gameport cannot be null');
        }
        if (($gameport < 0)) {
            throw new \InvalidArgumentException('invalid value for $gameport when calling SteamServer., must be bigger than or equal to 0.');
        }

        $this->container['gameport'] = $gameport;

        return $this;
    }

    /**
     * Gets gametype
     *
     * @return string
     */
    public function getGametype()
    {
        return $this->container['gametype'];
    }

    /**
     * Sets gametype
     *
     * @param string $gametype Steam gametype tags
     *
     * @return self
     */
    public function setGametype($gametype)
    {
        if (is_null($gametype)) {
            throw new \InvalidArgumentException('non-nullable gametype cannot be null');
        }
        $this->container['gametype'] = $gametype;

        return $this;
    }

    /**
     * Gets map
     *
     * @return string
     */
    public function getMap()
    {
        return $this->container['map'];
    }

    /**
     * Sets map
     *
     * @param string $map Current map
     *
     * @return self
     */
    public function setMap($map)
    {
        if (is_null($map)) {
            throw new \InvalidArgumentException('non-nullable map cannot be null');
        }
        $this->container['map'] = $map;

        return $this;
    }

    /**
     * Gets max_players
     *
     * @return int
     */
    public function getMaxPlayers()
    {
        return $this->container['max_players'];
    }

    /**
     * Sets max_players
     *
     * @param int $max_players Maximum player count
     *
     * @return self
     */
    public function setMaxPlayers($max_players)
    {
        if (is_null($max_players)) {
            throw new \InvalidArgumentException('non-nullable max_players cannot be null');
        }
        if (($max_players < 0)) {
            throw new \InvalidArgumentException('invalid value for $max_players when calling SteamServer., must be bigger than or equal to 0.');
        }

        $this->container['max_players'] = $max_players;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name Server name as advertised to Steam
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets os
     *
     * @return string
     */
    public function getOs()
    {
        return $this->container['os'];
    }

    /**
     * Sets os
     *
     * @param string $os Operating system the server is running on (e.g. `l` for Linux, `w` for Windows)
     *
     * @return self
     */
    public function setOs($os)
    {
        if (is_null($os)) {
            throw new \InvalidArgumentException('non-nullable os cannot be null');
        }
        $this->container['os'] = $os;

        return $this;
    }

    /**
     * Gets players
     *
     * @return int
     */
    public function getPlayers()
    {
        return $this->container['players'];
    }

    /**
     * Sets players
     *
     * @param int $players Current player count
     *
     * @return self
     */
    public function setPlayers($players)
    {
        if (is_null($players)) {
            throw new \InvalidArgumentException('non-nullable players cannot be null');
        }
        if (($players < 0)) {
            throw new \InvalidArgumentException('invalid value for $players when calling SteamServer., must be bigger than or equal to 0.');
        }

        $this->container['players'] = $players;

        return $this;
    }

    /**
     * Gets product
     *
     * @return string
     */
    public function getProduct()
    {
        return $this->container['product'];
    }

    /**
     * Sets product
     *
     * @param string $product Product identifier reported by the server
     *
     * @return self
     */
    public function setProduct($product)
    {
        if (is_null($product)) {
            throw new \InvalidArgumentException('non-nullable product cannot be null');
        }
        $this->container['product'] = $product;

        return $this;
    }

    /**
     * Gets region
     *
     * @return int
     */
    public function getRegion()
    {
        return $this->container['region'];
    }

    /**
     * Sets region
     *
     * @param int $region Steam region code reported by the server
     *
     * @return self
     */
    public function setRegion($region)
    {
        if (is_null($region)) {
            throw new \InvalidArgumentException('non-nullable region cannot be null');
        }
        $this->container['region'] = $region;

        return $this;
    }

    /**
     * Gets secure
     *
     * @return bool
     */
    public function getSecure()
    {
        return $this->container['secure'];
    }

    /**
     * Sets secure
     *
     * @param bool $secure Whether the server is VAC-secured
     *
     * @return self
     */
    public function setSecure($secure)
    {
        if (is_null($secure)) {
            throw new \InvalidArgumentException('non-nullable secure cannot be null');
        }
        $this->container['secure'] = $secure;

        return $this;
    }

    /**
     * Gets steamid
     *
     * @return string
     */
    public function getSteamid()
    {
        return $this->container['steamid'];
    }

    /**
     * Sets steamid
     *
     * @param string $steamid `SteamID` of the server
     *
     * @return self
     */
    public function setSteamid($steamid)
    {
        if (is_null($steamid)) {
            throw new \InvalidArgumentException('non-nullable steamid cannot be null');
        }
        $this->container['steamid'] = $steamid;

        return $this;
    }

    /**
     * Gets version
     *
     * @return string
     */
    public function getVersion()
    {
        return $this->container['version'];
    }

    /**
     * Sets version
     *
     * @param string $version Server build version
     *
     * @return self
     */
    public function setVersion($version)
    {
        if (is_null($version)) {
            throw new \InvalidArgumentException('non-nullable version cannot be null');
        }
        $this->container['version'] = $version;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


