/*
Deadlock API

Testing RanksAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package deadlock_api_client

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/deadlock-api/openapi-clients"
)

func Test_deadlock_api_client_RanksAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test RanksAPIService GetRank", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var tier int32

		resp, httpRes, err := apiClient.RanksAPI.GetRank(context.Background(), tier).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RanksAPIService ListRanks", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.RanksAPI.ListRanks(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RanksAPIService SubrankImage", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var tier int32
		var subrank int32

		resp, httpRes, err := apiClient.RanksAPI.SubrankImage(context.Background(), tier, subrank).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
