## AnalyticsApi

### Ability Order Stats
## Ability Order Stats
GET https://api.deadlock-api.com/v1/analytics/ability-order-stats?heroId={{heroId}}&gameMode={{gameMode}}&matchMode={{matchMode}}&minUnixTimestamp={{minUnixTimestamp}}&maxUnixTimestamp={{maxUnixTimestamp}}&minDurationS={{minDurationS}}&maxDurationS={{maxDurationS}}&minAbilityUpgrades={{minAbilityUpgrades}}&maxAbilityUpgrades={{maxAbilityUpgrades}}&minNetworth={{minNetworth}}&maxNetworth={{maxNetworth}}&minAverageBadge={{minAverageBadge}}&maxAverageBadge={{maxAverageBadge}}&minMatchId={{minMatchId}}&maxMatchId={{maxMatchId}}&minMatches={{minMatches}}&accountId={{accountId}}&accountIds={{accountIds}}&includeItemIds={{includeItemIds}}&excludeItemIds={{excludeItemIds}}
Accept: application/json

### Badge Distribution
## Badge Distribution
GET https://api.deadlock-api.com/v1/analytics/badge-distribution?gameMode={{gameMode}}&matchMode={{matchMode}}&minUnixTimestamp={{minUnixTimestamp}}&maxUnixTimestamp={{maxUnixTimestamp}}&minDurationS={{minDurationS}}&maxDurationS={{maxDurationS}}&isHighSkillRangeParties={{isHighSkillRangeParties}}&isLowPriPool={{isLowPriPool}}&isNewPlayerPool={{isNewPlayerPool}}&minMatchId={{minMatchId}}&maxMatchId={{maxMatchId}}
Accept: application/json

### Build Item Stats
## Build Item Stats
GET https://api.deadlock-api.com/v1/analytics/build-item-stats?heroId={{heroId}}&minLastUpdatedUnixTimestamp={{minLastUpdatedUnixTimestamp}}&maxLastUpdatedUnixTimestamp={{maxLastUpdatedUnixTimestamp}}
Accept: application/json

### Game Stats
## Game Stats
GET https://api.deadlock-api.com/v1/analytics/game-stats?bucket={{bucket}}&gameMode={{gameMode}}&matchMode={{matchMode}}&minUnixTimestamp={{minUnixTimestamp}}&maxUnixTimestamp={{maxUnixTimestamp}}&minDurationS={{minDurationS}}&maxDurationS={{maxDurationS}}&minAverageBadge={{minAverageBadge}}&maxAverageBadge={{maxAverageBadge}}&minMatchId={{minMatchId}}&maxMatchId={{maxMatchId}}&minNetworth={{minNetworth}}&maxNetworth={{maxNetworth}}&heroIds={{heroIds}}&includeItemIds={{includeItemIds}}&excludeItemIds={{excludeItemIds}}&accountIds={{accountIds}}
Accept: application/json

### Hero Ban Stats
## Hero Ban Stats
GET https://api.deadlock-api.com/v1/analytics/hero-ban-stats?matchMode={{matchMode}}&bucket={{bucket}}&minUnixTimestamp={{minUnixTimestamp}}&maxUnixTimestamp={{maxUnixTimestamp}}&minDurationS={{minDurationS}}&maxDurationS={{maxDurationS}}&minAverageBadge={{minAverageBadge}}&maxAverageBadge={{maxAverageBadge}}&minMatchId={{minMatchId}}&maxMatchId={{maxMatchId}}
Accept: application/json

### Hero Build Stats
## Hero Build Stats
GET https://api.deadlock-api.com/v1/analytics/hero-build-stats/{{hero_id}}?matchMode={{matchMode}}&minUnixTimestamp={{minUnixTimestamp}}&maxUnixTimestamp={{maxUnixTimestamp}}&minDurationS={{minDurationS}}&maxDurationS={{maxDurationS}}&minAverageBadge={{minAverageBadge}}&maxAverageBadge={{maxAverageBadge}}&minMatchId={{minMatchId}}&maxMatchId={{maxMatchId}}&heroBuildId={{heroBuildId}}&minMatches={{minMatches}}&accountId={{accountId}}&accountIds={{accountIds}}
Accept: application/json

### Hero Comb Stats
## Hero Comb Stats
GET https://api.deadlock-api.com/v1/analytics/hero-comb-stats?gameMode={{gameMode}}&matchMode={{matchMode}}&minUnixTimestamp={{minUnixTimestamp}}&maxUnixTimestamp={{maxUnixTimestamp}}&minDurationS={{minDurationS}}&maxDurationS={{maxDurationS}}&minNetworth={{minNetworth}}&maxNetworth={{maxNetworth}}&minAverageBadge={{minAverageBadge}}&maxAverageBadge={{maxAverageBadge}}&minMatchId={{minMatchId}}&maxMatchId={{maxMatchId}}&includeHeroIds={{includeHeroIds}}&excludeHeroIds={{excludeHeroIds}}&includeEnemyHeroIds={{includeEnemyHeroIds}}&excludeEnemyHeroIds={{excludeEnemyHeroIds}}&minMatches={{minMatches}}&maxMatches={{maxMatches}}&combSize={{combSize}}&accountId={{accountId}}&accountIds={{accountIds}}
Accept: application/json

### Hero Counter Stats
## Hero Counter Stats
GET https://api.deadlock-api.com/v1/analytics/hero-counter-stats?gameMode={{gameMode}}&matchMode={{matchMode}}&minUnixTimestamp={{minUnixTimestamp}}&maxUnixTimestamp={{maxUnixTimestamp}}&minDurationS={{minDurationS}}&maxDurationS={{maxDurationS}}&minNetworth={{minNetworth}}&maxNetworth={{maxNetworth}}&minEnemyNetworth={{minEnemyNetworth}}&maxEnemyNetworth={{maxEnemyNetworth}}&minAverageBadge={{minAverageBadge}}&maxAverageBadge={{maxAverageBadge}}&minMatchId={{minMatchId}}&maxMatchId={{maxMatchId}}&sameLaneFilter={{sameLaneFilter}}&minMatches={{minMatches}}&maxMatches={{maxMatches}}&accountId={{accountId}}&accountIds={{accountIds}}
Accept: application/json

### Hero Scoreboard
## Hero Scoreboard
GET https://api.deadlock-api.com/v1/analytics/scoreboards/heroes?sortBy={{sortBy}}&sortDirection={{sortDirection}}&gameMode={{gameMode}}&matchMode={{matchMode}}&minMatches={{minMatches}}&minUnixTimestamp={{minUnixTimestamp}}&maxUnixTimestamp={{maxUnixTimestamp}}&minDurationS={{minDurationS}}&maxDurationS={{maxDurationS}}&minNetworth={{minNetworth}}&maxNetworth={{maxNetworth}}&minAverageBadge={{minAverageBadge}}&maxAverageBadge={{maxAverageBadge}}&minMatchId={{minMatchId}}&maxMatchId={{maxMatchId}}&accountId={{accountId}}&accountIds={{accountIds}}
Accept: application/json

### Hero Stats
## Hero Stats
GET https://api.deadlock-api.com/v1/analytics/hero-stats?bucket={{bucket}}&gameMode={{gameMode}}&matchMode={{matchMode}}&minUnixTimestamp={{minUnixTimestamp}}&maxUnixTimestamp={{maxUnixTimestamp}}&minDurationS={{minDurationS}}&maxDurationS={{maxDurationS}}&minNetworth={{minNetworth}}&maxNetworth={{maxNetworth}}&minAverageBadge={{minAverageBadge}}&maxAverageBadge={{maxAverageBadge}}&minMatchId={{minMatchId}}&maxMatchId={{maxMatchId}}&minHeroMatches={{minHeroMatches}}&maxHeroMatches={{maxHeroMatches}}&minHeroMatchesTotal={{minHeroMatchesTotal}}&maxHeroMatchesTotal={{maxHeroMatchesTotal}}&includeItemIds={{includeItemIds}}&excludeItemIds={{excludeItemIds}}&accountId={{accountId}}&accountIds={{accountIds}}
Accept: application/json

### Hero Synergy Stats
## Hero Synergy Stats
GET https://api.deadlock-api.com/v1/analytics/hero-synergy-stats?gameMode={{gameMode}}&matchMode={{matchMode}}&minUnixTimestamp={{minUnixTimestamp}}&maxUnixTimestamp={{maxUnixTimestamp}}&minDurationS={{minDurationS}}&maxDurationS={{maxDurationS}}&minNetworth={{minNetworth}}&maxNetworth={{maxNetworth}}&minAverageBadge={{minAverageBadge}}&maxAverageBadge={{maxAverageBadge}}&minMatchId={{minMatchId}}&maxMatchId={{maxMatchId}}&sameLaneFilter={{sameLaneFilter}}&minMatches={{minMatches}}&maxMatches={{maxMatches}}&accountId={{accountId}}&accountIds={{accountIds}}
Accept: application/json

### Item Flow Stats
## Item Flow Stats
GET https://api.deadlock-api.com/v1/analytics/item-flow-stats?phaseIntervalS={{phaseIntervalS}}&phaseCount={{phaseCount}}&gameMode={{gameMode}}&matchMode={{matchMode}}&heroIds={{heroIds}}&minUnixTimestamp={{minUnixTimestamp}}&maxUnixTimestamp={{maxUnixTimestamp}}&minDurationS={{minDurationS}}&maxDurationS={{maxDurationS}}&minNetworth={{minNetworth}}&maxNetworth={{maxNetworth}}&minAverageBadge={{minAverageBadge}}&maxAverageBadge={{maxAverageBadge}}&minMatchId={{minMatchId}}&maxMatchId={{maxMatchId}}&minMatches={{minMatches}}&accountIds={{accountIds}}&includeItemIds={{includeItemIds}}&excludeItemIds={{excludeItemIds}}&lockedItemIds={{lockedItemIds}}&lockedColumns={{lockedColumns}}
Accept: application/json

### Item Permutation Stats
## Item Permutation Stats
GET https://api.deadlock-api.com/v1/analytics/item-permutation-stats?itemIds={{itemIds}}&combSize={{combSize}}&minMatches={{minMatches}}&maxMatches={{maxMatches}}&gameMode={{gameMode}}&matchMode={{matchMode}}&heroIds={{heroIds}}&heroId={{heroId}}&minUnixTimestamp={{minUnixTimestamp}}&maxUnixTimestamp={{maxUnixTimestamp}}&minDurationS={{minDurationS}}&maxDurationS={{maxDurationS}}&minNetworth={{minNetworth}}&maxNetworth={{maxNetworth}}&minAverageBadge={{minAverageBadge}}&maxAverageBadge={{maxAverageBadge}}&minMatchId={{minMatchId}}&maxMatchId={{maxMatchId}}&accountId={{accountId}}&accountIds={{accountIds}}
Accept: application/json

### Item Stats
## Item Stats
GET https://api.deadlock-api.com/v1/analytics/item-stats?bucket={{bucket}}&gameMode={{gameMode}}&matchMode={{matchMode}}&heroIds={{heroIds}}&heroId={{heroId}}&enemyHeroIds={{enemyHeroIds}}&enemyHeroIdsAllMatch={{enemyHeroIdsAllMatch}}&minEnemyNetworth={{minEnemyNetworth}}&maxEnemyNetworth={{maxEnemyNetworth}}&sameLaneFilter={{sameLaneFilter}}&minUnixTimestamp={{minUnixTimestamp}}&maxUnixTimestamp={{maxUnixTimestamp}}&minDurationS={{minDurationS}}&maxDurationS={{maxDurationS}}&minNetworth={{minNetworth}}&maxNetworth={{maxNetworth}}&minAverageBadge={{minAverageBadge}}&maxAverageBadge={{maxAverageBadge}}&minMatchId={{minMatchId}}&maxMatchId={{maxMatchId}}&includeItemIds={{includeItemIds}}&excludeItemIds={{excludeItemIds}}&minMatches={{minMatches}}&maxMatches={{maxMatches}}&accountId={{accountId}}&accountIds={{accountIds}}&minBoughtAtS={{minBoughtAtS}}&maxBoughtAtS={{maxBoughtAtS}}&itemOrder={{itemOrder}}
Accept: application/json

### Kill Death Stats
## Kill Death Stats
GET https://api.deadlock-api.com/v1/analytics/kill-death-stats?team={{team}}&gameMode={{gameMode}}&matchMode={{matchMode}}&minUnixTimestamp={{minUnixTimestamp}}&maxUnixTimestamp={{maxUnixTimestamp}}&minDurationS={{minDurationS}}&maxDurationS={{maxDurationS}}&accountIds={{accountIds}}&heroIds={{heroIds}}&minNetworth={{minNetworth}}&maxNetworth={{maxNetworth}}&isHighSkillRangeParties={{isHighSkillRangeParties}}&isLowPriPool={{isLowPriPool}}&isNewPlayerPool={{isNewPlayerPool}}&minMatchId={{minMatchId}}&maxMatchId={{maxMatchId}}&minAverageBadge={{minAverageBadge}}&maxAverageBadge={{maxAverageBadge}}&minKillsPerRaster={{minKillsPerRaster}}&maxKillsPerRaster={{maxKillsPerRaster}}&minDeathsPerRaster={{minDeathsPerRaster}}&maxDeathsPerRaster={{maxDeathsPerRaster}}&minGameTimeS={{minGameTimeS}}&maxGameTimeS={{maxGameTimeS}}
Accept: application/json

### Lane Matchup Stats (Subject to Change)
## Lane Matchup Stats (Subject to Change)
GET https://api.deadlock-api.com/v1/analytics/lane-matchup-stats?gameMode={{gameMode}}&matchMode={{matchMode}}&minUnixTimestamp={{minUnixTimestamp}}&maxUnixTimestamp={{maxUnixTimestamp}}&minDurationS={{minDurationS}}&maxDurationS={{maxDurationS}}&minAverageBadge={{minAverageBadge}}&maxAverageBadge={{maxAverageBadge}}&minMatchId={{minMatchId}}&maxMatchId={{maxMatchId}}&sampleTimeS={{sampleTimeS}}&assignedLanes={{assignedLanes}}&heroIds={{heroIds}}&enemyHeroIds={{enemyHeroIds}}&stats={{stats}}&groupBy={{groupBy}}&minMatches={{minMatches}}&maxMatches={{maxMatches}}&accountIds={{accountIds}}
Accept: application/json

### Lane Soul Curve (Subject to Change)
## Lane Soul Curve (Subject to Change)
GET https://api.deadlock-api.com/v1/analytics/lane-soul-curve?gameMode={{gameMode}}&matchMode={{matchMode}}&minUnixTimestamp={{minUnixTimestamp}}&maxUnixTimestamp={{maxUnixTimestamp}}&minDurationS={{minDurationS}}&maxDurationS={{maxDurationS}}&minAverageBadge={{minAverageBadge}}&maxAverageBadge={{maxAverageBadge}}&minMatchId={{minMatchId}}&maxMatchId={{maxMatchId}}&minTimeS={{minTimeS}}&maxTimeS={{maxTimeS}}&assignedLanes={{assignedLanes}}&heroIds={{heroIds}}&enemyHeroIds={{enemyHeroIds}}&stats={{stats}}&groupBy={{groupBy}}&minMatches={{minMatches}}&maxMatches={{maxMatches}}&accountIds={{accountIds}}
Accept: application/json

### Player Performance Curve
## Player Performance Curve
GET https://api.deadlock-api.com/v1/analytics/player-performance-curve?resolution={{resolution}}&gameMode={{gameMode}}&matchMode={{matchMode}}&minUnixTimestamp={{minUnixTimestamp}}&maxUnixTimestamp={{maxUnixTimestamp}}&minDurationS={{minDurationS}}&maxDurationS={{maxDurationS}}&minNetworth={{minNetworth}}&maxNetworth={{maxNetworth}}&minAverageBadge={{minAverageBadge}}&maxAverageBadge={{maxAverageBadge}}&minMatchId={{minMatchId}}&maxMatchId={{maxMatchId}}&heroIds={{heroIds}}&includeItemIds={{includeItemIds}}&excludeItemIds={{excludeItemIds}}&accountIds={{accountIds}}
Accept: application/json

### Player Scoreboard
## Player Scoreboard
GET https://api.deadlock-api.com/v1/analytics/scoreboards/players?sortBy={{sortBy}}&sortDirection={{sortDirection}}&gameMode={{gameMode}}&matchMode={{matchMode}}&heroId={{heroId}}&minMatches={{minMatches}}&maxMatches={{maxMatches}}&minUnixTimestamp={{minUnixTimestamp}}&maxUnixTimestamp={{maxUnixTimestamp}}&minDurationS={{minDurationS}}&maxDurationS={{maxDurationS}}&minNetworth={{minNetworth}}&maxNetworth={{maxNetworth}}&minAverageBadge={{minAverageBadge}}&maxAverageBadge={{maxAverageBadge}}&minMatchId={{minMatchId}}&maxMatchId={{maxMatchId}}&start={{start}}&limit={{limit}}&accountIds={{accountIds}}
Accept: application/json

### Player Stats Metrics
## Player Stats Metrics
GET https://api.deadlock-api.com/v1/analytics/player-stats/metrics?heroIds={{heroIds}}&gameMode={{gameMode}}&matchMode={{matchMode}}&minUnixTimestamp={{minUnixTimestamp}}&maxUnixTimestamp={{maxUnixTimestamp}}&minDurationS={{minDurationS}}&maxDurationS={{maxDurationS}}&minNetworth={{minNetworth}}&maxNetworth={{maxNetworth}}&minAverageBadge={{minAverageBadge}}&maxAverageBadge={{maxAverageBadge}}&minMatchId={{minMatchId}}&maxMatchId={{maxMatchId}}&maxMatches={{maxMatches}}&includeItemIds={{includeItemIds}}&excludeItemIds={{excludeItemIds}}&accountIds={{accountIds}}
Accept: application/json
