## MMRApi

### Batch Hero MMR (Deprecated)
## Batch Hero MMR (Deprecated)
GET https://api.deadlock-api.com/v1/players/mmr/{{hero_id}}?accountIds={{accountIds}}&maxMatchId={{maxMatchId}}
Accept: application/json

### Hero MMR Distribution (Deprecated)
## Hero MMR Distribution (Deprecated)
GET https://api.deadlock-api.com/v1/players/mmr/distribution/{{hero_id}}?minUnixTimestamp={{minUnixTimestamp}}&maxUnixTimestamp={{maxUnixTimestamp}}&minDurationS={{minDurationS}}&maxDurationS={{maxDurationS}}&isHighSkillRangeParties={{isHighSkillRangeParties}}&isLowPriPool={{isLowPriPool}}&isNewPlayerPool={{isNewPlayerPool}}&minMatchId={{minMatchId}}&maxMatchId={{maxMatchId}}
Accept: application/json

### Hero MMR History (Deprecated)
## Hero MMR History (Deprecated)
GET https://api.deadlock-api.com/v1/players/{{account_id}}/mmr-history/{{hero_id}}
Accept: application/json

### Batch MMR (Deprecated)
## Batch MMR (Deprecated)
GET https://api.deadlock-api.com/v1/players/mmr?accountIds={{accountIds}}&maxMatchId={{maxMatchId}}
Accept: application/json

### MMR Distribution (Deprecated)
## MMR Distribution (Deprecated)
GET https://api.deadlock-api.com/v1/players/mmr/distribution?minUnixTimestamp={{minUnixTimestamp}}&maxUnixTimestamp={{maxUnixTimestamp}}&minDurationS={{minDurationS}}&maxDurationS={{maxDurationS}}&isHighSkillRangeParties={{isHighSkillRangeParties}}&isLowPriPool={{isLowPriPool}}&isNewPlayerPool={{isNewPlayerPool}}&minMatchId={{minMatchId}}&maxMatchId={{maxMatchId}}
Accept: application/json

### MMR History (Deprecated)
## MMR History (Deprecated)
GET https://api.deadlock-api.com/v1/players/{{account_id}}/mmr-history
Accept: application/json
