## PlayersApi

### Account Stats
## Account Stats
GET https://api.deadlock-api.com/v1/players/{{account_id}}/account-stats
Accept: application/json

### Card
## Card
GET https://api.deadlock-api.com/v1/players/{{account_id}}/card
Accept: application/json

### Enemy Stats
## Enemy Stats
GET https://api.deadlock-api.com/v1/players/{{account_id}}/enemy-stats?gameMode={{gameMode}}&minUnixTimestamp={{minUnixTimestamp}}&maxUnixTimestamp={{maxUnixTimestamp}}&minDurationS={{minDurationS}}&maxDurationS={{maxDurationS}}&minMatchId={{minMatchId}}&maxMatchId={{maxMatchId}}&minMatchesPlayed={{minMatchesPlayed}}&maxMatchesPlayed={{maxMatchesPlayed}}
Accept: application/json

### Match History
## Match History
GET https://api.deadlock-api.com/v1/players/{{account_id}}/match-history?forceRefetch={{forceRefetch}}
Accept: application/json

### Mate Stats
## Mate Stats
GET https://api.deadlock-api.com/v1/players/{{account_id}}/mate-stats?gameMode={{gameMode}}&minUnixTimestamp={{minUnixTimestamp}}&maxUnixTimestamp={{maxUnixTimestamp}}&minDurationS={{minDurationS}}&maxDurationS={{maxDurationS}}&minMatchId={{minMatchId}}&maxMatchId={{maxMatchId}}&minMatchesPlayed={{minMatchesPlayed}}&maxMatchesPlayed={{maxMatchesPlayed}}&sameParty={{sameParty}}
Accept: application/json

### Hero Stats
## Hero Stats
GET https://api.deadlock-api.com/v1/players/hero-stats?accountIds={{accountIds}}&gameMode={{gameMode}}&matchMode={{matchMode}}&heroIds={{heroIds}}&minUnixTimestamp={{minUnixTimestamp}}&maxUnixTimestamp={{maxUnixTimestamp}}&minDurationS={{minDurationS}}&maxDurationS={{maxDurationS}}&minNetworth={{minNetworth}}&maxNetworth={{maxNetworth}}&minAverageBadge={{minAverageBadge}}&maxAverageBadge={{maxAverageBadge}}&minMatchId={{minMatchId}}&maxMatchId={{maxMatchId}}
Accept: application/json

### Rank
## Rank
GET https://api.deadlock-api.com/v1/players/{{account_id}}/rank
Accept: application/json

### Rank Avg Image
## Rank Avg Image
GET https://api.deadlock-api.com/v1/players/rank/image?accountIds={{accountIds}}&format={{format}}
Accept: image/png
Accept: image/webp

### Rank Image
## Rank Image
GET https://api.deadlock-api.com/v1/players/{{account_id}}/rank/image?format={{format}}
Accept: image/png
Accept: image/webp

### Rank Predict (Deprecated)
## Rank Predict (Deprecated)
GET https://api.deadlock-api.com/v1/players/{{account_id}}/rank-predict
Accept: application/json

### Rank Predict Avg Image (Deprecated)
## Rank Predict Avg Image (Deprecated)
GET https://api.deadlock-api.com/v1/players/rank-predict/image?accountIds={{accountIds}}&format={{format}}
Accept: image/png
Accept: image/webp

### Rank Predict Image (Deprecated)
## Rank Predict Image (Deprecated)
GET https://api.deadlock-api.com/v1/players/{{account_id}}/rank-predict/image?format={{format}}
Accept: image/png
Accept: image/webp
