/*
 * Deadlock API
 *
 *  ## API Clients  We have auto generated and updated clients for many languages. You can find them here: [https://github.com/deadlock-api/openapi-clients](https://github.com/deadlock-api/openapi-clients)  ## Support the Deadlock API  Whether you're building your own database, developing data science projects, or enhancing your website with game and player analytics, the Deadlock API has the data you need.  Your sponsorship helps keep this resource open, free and future-proof for everyone. By supporting the Deadlock API, you will enable continued development, new features and reliable access for developers, analysts and streamers worldwide.  Help us continue to provide the data you need - sponsor the Deadlock API today!  **-> You can Sponsor the Deadlock API on [Patreon](https://www.patreon.com/c/user?u=68961896) or [GitHub](https://github.com/sponsors/raimannma)**  ## Disclaimer _deadlock-api.com is not endorsed by Valve and does not reflect the views or opinions of Valve or anyone officially involved in producing or managing Valve properties. Valve and all associated properties are trademarks or registered trademarks of Valve Corporation_         
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LaneSoulCurve : **⚠️ Subject to change:** newly added, fields may change or be removed without notice.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LaneSoulCurve {
    /// The lane the matchup was played in, or `0` when `assigned_lane` was grouped away. See the `lane_info` array of <https://api.deadlock-api.com/v1/assets/generic-data>.
    #[serde(rename = "assigned_lane")]
    pub assigned_lane: u32,
    /// The ascending hero id pair they laned against, or empty when grouped away.
    #[serde(rename = "enemy_hero_ids")]
    pub enemy_hero_ids: Vec<u32>,
    /// The ascending hero id pair that shared the lane, or empty when grouped away. See more: <https://api.deadlock-api.com/v1/assets/heroes>
    #[serde(rename = "hero_ids")]
    pub hero_ids: Vec<u32>,
    /// Lane matchups behind the row, counted at its *first* sample. This is what `min_matches` and `max_matches` filter on, so it does not move when the requested time range changes; read `sample_matches` for what any individual point rests on.
    #[serde(rename = "matches_played")]
    pub matches_played: u64,
    /// Mean souls the duo is ahead by at the matching entry of `sample_times_s`. Negative means behind. Same length as `sample_times_s`.
    #[serde(rename = "net_worth_diff")]
    pub net_worth_diff: Vec<f64>,
    /// Population standard deviation of the lead across the counted matchups, at the matching entry of `sample_times_s`. Same length as `sample_times_s`.  Spread between individual games, not uncertainty about the mean: it stays wide however many matchups are counted, because lane outcomes genuinely differ that much.
    #[serde(rename = "net_worth_diff_std")]
    pub net_worth_diff_std: Vec<f64>,
    /// How many lane matchups were still running at the matching entry of `sample_times_s`. Falls off towards the end of the curve as shorter matches drop out.
    #[serde(rename = "sample_matches")]
    pub sample_matches: Vec<u64>,
    /// Seconds into the match each entry of the curves was sampled at, ascending.
    #[serde(rename = "sample_times_s")]
    pub sample_times_s: Vec<u32>,
    /// A curve per stat named in `stats`. Empty unless the parameter was set.
    #[serde(rename = "stats")]
    pub stats: std::collections::HashMap<String, models::LaneStatCurve>,
}

impl LaneSoulCurve {
    /// **⚠️ Subject to change:** newly added, fields may change or be removed without notice.
    pub fn new(assigned_lane: u32, enemy_hero_ids: Vec<u32>, hero_ids: Vec<u32>, matches_played: u64, net_worth_diff: Vec<f64>, net_worth_diff_std: Vec<f64>, sample_matches: Vec<u64>, sample_times_s: Vec<u32>, stats: std::collections::HashMap<String, models::LaneStatCurve>) -> LaneSoulCurve {
        LaneSoulCurve {
            assigned_lane,
            enemy_hero_ids,
            hero_ids,
            matches_played,
            net_worth_diff,
            net_worth_diff_std,
            sample_matches,
            sample_times_s,
            stats,
        }
    }
}

