// tslint:disable
/**
 * Deadlock API
 *  ## API Clients  We have auto generated and updated clients for many languages. You can find them here: [https://github.com/deadlock-api/openapi-clients](https://github.com/deadlock-api/openapi-clients)  ## Support the Deadlock API  Whether you\'re building your own database, developing data science projects, or enhancing your website with game and player analytics, the Deadlock API has the data you need.  Your sponsorship helps keep this resource open, free and future-proof for everyone. By supporting the Deadlock API, you will enable continued development, new features and reliable access for developers, analysts and streamers worldwide.  Help us continue to provide the data you need - sponsor the Deadlock API today!  **-> You can Sponsor the Deadlock API on [Patreon](https://www.patreon.com/c/user?u=68961896) or [GitHub](https://github.com/sponsors/raimannma)**  ## Disclaimer _deadlock-api.com is not endorsed by Valve and does not reflect the views or opinions of Valve or anyone officially involved in producing or managing Valve properties. Valve and all associated properties are trademarks or registered trademarks of Valve Corporation_         
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    LaneStatCurve,
    LaneStatCurveFromJSON,
    LaneStatCurveToJSON,
} from './';

/**
 * **⚠️ Subject to change:** newly added, fields may change or be removed without notice.
 * @export
 * @interface LaneSoulCurve
 */
export interface LaneSoulCurve  {
    /**
     * The lane the matchup was played in, or `0` when `assigned_lane` was grouped away. See the `lane_info` array of <https://api.deadlock-api.com/v1/assets/generic-data>.
     * @type {number}
     * @memberof LaneSoulCurve
     */
    assignedLane: number;
    /**
     * The ascending hero id pair they laned against, or empty when grouped away.
     * @type {Array<number>}
     * @memberof LaneSoulCurve
     */
    enemyHeroIds: Array<number>;
    /**
     * The ascending hero id pair that shared the lane, or empty when grouped away. See more: <https://api.deadlock-api.com/v1/assets/heroes>
     * @type {Array<number>}
     * @memberof LaneSoulCurve
     */
    heroIds: Array<number>;
    /**
     * Lane matchups behind the row, counted at its *first* sample. This is what `min_matches` and `max_matches` filter on, so it does not move when the requested time range changes; read `sample_matches` for what any individual point rests on.
     * @type {number}
     * @memberof LaneSoulCurve
     */
    matchesPlayed: number;
    /**
     * Mean souls the duo is ahead by at the matching entry of `sample_times_s`. Negative means behind. Same length as `sample_times_s`.
     * @type {Array<number>}
     * @memberof LaneSoulCurve
     */
    netWorthDiff: Array<number>;
    /**
     * Population standard deviation of the lead across the counted matchups, at the matching entry of `sample_times_s`. Same length as `sample_times_s`.  Spread between individual games, not uncertainty about the mean: it stays wide however many matchups are counted, because lane outcomes genuinely differ that much.
     * @type {Array<number>}
     * @memberof LaneSoulCurve
     */
    netWorthDiffStd: Array<number>;
    /**
     * How many lane matchups were still running at the matching entry of `sample_times_s`. Falls off towards the end of the curve as shorter matches drop out.
     * @type {Array<number>}
     * @memberof LaneSoulCurve
     */
    sampleMatches: Array<number>;
    /**
     * Seconds into the match each entry of the curves was sampled at, ascending.
     * @type {Array<number>}
     * @memberof LaneSoulCurve
     */
    sampleTimesS: Array<number>;
    /**
     * A curve per stat named in `stats`. Empty unless the parameter was set.
     * @type {{ [key: string]: LaneStatCurve; }}
     * @memberof LaneSoulCurve
     */
    stats: { [key: string]: LaneStatCurve; };
}

export function LaneSoulCurveFromJSON(json: any): LaneSoulCurve {
    return {
        'assignedLane': json['assigned_lane'],
        'enemyHeroIds': json['enemy_hero_ids'],
        'heroIds': json['hero_ids'],
        'matchesPlayed': json['matches_played'],
        'netWorthDiff': json['net_worth_diff'],
        'netWorthDiffStd': json['net_worth_diff_std'],
        'sampleMatches': json['sample_matches'],
        'sampleTimesS': json['sample_times_s'],
        'stats': mapValues(json['stats'], LaneStatCurveFromJSON),
    };
}

export function LaneSoulCurveToJSON(value?: LaneSoulCurve): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'assigned_lane': value.assignedLane,
        'enemy_hero_ids': value.enemyHeroIds,
        'hero_ids': value.heroIds,
        'matches_played': value.matchesPlayed,
        'net_worth_diff': value.netWorthDiff,
        'net_worth_diff_std': value.netWorthDiffStd,
        'sample_matches': value.sampleMatches,
        'sample_times_s': value.sampleTimesS,
        'stats': mapValues(value.stats, LaneStatCurveToJSON),
    };
}


