// tslint:disable
/**
 * Deadlock API
 *  ## API Clients  We have auto generated and updated clients for many languages. You can find them here: [https://github.com/deadlock-api/openapi-clients](https://github.com/deadlock-api/openapi-clients)  ## Support the Deadlock API  Whether you\'re building your own database, developing data science projects, or enhancing your website with game and player analytics, the Deadlock API has the data you need.  Your sponsorship helps keep this resource open, free and future-proof for everyone. By supporting the Deadlock API, you will enable continued development, new features and reliable access for developers, analysts and streamers worldwide.  Help us continue to provide the data you need - sponsor the Deadlock API today!  **-> You can Sponsor the Deadlock API on [Patreon](https://www.patreon.com/c/user?u=68961896) or [GitHub](https://github.com/sponsors/raimannma)**  ## Disclaimer _deadlock-api.com is not endorsed by Valve and does not reflect the views or opinions of Valve or anyone officially involved in producing or managing Valve properties. Valve and all associated properties are trademarks or registered trademarks of Valve Corporation_         
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    LaneMatchupStat,
    LaneMatchupStatFromJSON,
    LaneMatchupStatToJSON,
} from './';

/**
 * **⚠️ Subject to change:** newly added, fields may change or be removed without notice.
 * @export
 * @interface LaneMatchupStats
 */
export interface LaneMatchupStats  {
    /**
     * The lane the matchup was played in, or `0` when `assigned_lane` was grouped away. See the `lane_info` array of <https://api.deadlock-api.com/v1/assets/generic-data>.
     * @type {number}
     * @memberof LaneMatchupStats
     */
    assignedLane: number;
    /**
     * The ascending hero id pair they laned against, or empty when grouped away.
     * @type {Array<number>}
     * @memberof LaneMatchupStats
     */
    enemyHeroIds: Array<number>;
    /**
     * The ascending hero id pair that shared the lane, or empty when grouped away. See more: <https://api.deadlock-api.com/v1/assets/heroes>
     * @type {Array<number>}
     * @memberof LaneMatchupStats
     */
    heroIds: Array<number>;
    /**
     * The total number of lane matchups between `hero_ids` and `enemy_hero_ids` in this lane.
     * @type {number}
     * @memberof LaneMatchupStats
     */
    matchesPlayed: number;
    /**
     * Mean souls the duo is ahead by at `sample_time_s`, against that duo. Negative means behind. `0` when no counted matchup lasted that long.
     * @type {number}
     * @memberof LaneMatchupStats
     */
    netWorthDiff: number;
    /**
     * How many of `matches_played` lasted to `sample_time_s` with all four players still in. Every reading on this row rests on those matchups only.
     * @type {number}
     * @memberof LaneMatchupStats
     */
    sampleMatches: number;
    /**
     * Seconds into the match the stat readings were taken at. Echoes the `sample_time_s` parameter.
     * @type {number}
     * @memberof LaneMatchupStats
     */
    sampleTimeS: number;
    /**
     * A reading per stat named in `stats`. Empty unless the parameter was set.
     * @type {{ [key: string]: LaneMatchupStat; }}
     * @memberof LaneMatchupStats
     */
    stats: { [key: string]: LaneMatchupStat; };
    /**
     * The number of matches `hero_ids` won against `enemy_hero_ids` in this lane.
     * @type {number}
     * @memberof LaneMatchupStats
     */
    wins: number;
}

export function LaneMatchupStatsFromJSON(json: any): LaneMatchupStats {
    return {
        'assignedLane': json['assigned_lane'],
        'enemyHeroIds': json['enemy_hero_ids'],
        'heroIds': json['hero_ids'],
        'matchesPlayed': json['matches_played'],
        'netWorthDiff': json['net_worth_diff'],
        'sampleMatches': json['sample_matches'],
        'sampleTimeS': json['sample_time_s'],
        'stats': mapValues(json['stats'], LaneMatchupStatFromJSON),
        'wins': json['wins'],
    };
}

export function LaneMatchupStatsToJSON(value?: LaneMatchupStats): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'assigned_lane': value.assignedLane,
        'enemy_hero_ids': value.enemyHeroIds,
        'hero_ids': value.heroIds,
        'matches_played': value.matchesPlayed,
        'net_worth_diff': value.netWorthDiff,
        'sample_matches': value.sampleMatches,
        'sample_time_s': value.sampleTimeS,
        'stats': mapValues(value.stats, LaneMatchupStatToJSON),
        'wins': value.wins,
    };
}


