/* tslint:disable */
/* eslint-disable */
/**
 * Deadlock API
 *  ## API Clients  We have auto generated and updated clients for many languages. You can find them here: [https://github.com/deadlock-api/openapi-clients](https://github.com/deadlock-api/openapi-clients)  ## Support the Deadlock API  Whether you\'re building your own database, developing data science projects, or enhancing your website with game and player analytics, the Deadlock API has the data you need.  Your sponsorship helps keep this resource open, free and future-proof for everyone. By supporting the Deadlock API, you will enable continued development, new features and reliable access for developers, analysts and streamers worldwide.  Help us continue to provide the data you need - sponsor the Deadlock API today!  **-> You can Sponsor the Deadlock API on [Patreon](https://www.patreon.com/c/user?u=68961896) or [GitHub](https://github.com/sponsors/raimannma)**  ## Disclaimer _deadlock-api.com is not endorsed by Valve and does not reflect the views or opinions of Valve or anyone officially involved in producing or managing Valve properties. Valve and all associated properties are trademarks or registered trademarks of Valve Corporation_         
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration.js';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common.js';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base.js';
// @ts-ignore
import type { DemoQueryJobResponse } from '../models/index.js';
// @ts-ignore
import type { DemoQueryRequest } from '../models/index.js';
// @ts-ignore
import type { DemoQueryStatusResponse } from '../models/index.js';
// @ts-ignore
import type { DemoSchemaResponse } from '../models/index.js';
/**
 * DemoApi - axios parameter creator
 */
export const DemoApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         *  Run a SQL query over a match\'s **live** broadcast and stream result rows over Server-Sent Events as the match plays, instead of waiting for the demo to finish (see the async `/demo/query`).  Provide either `match_id` (the server spectates the lobby to obtain the broadcast URL) or an explicit `broadcast_url` from `/live/urls`.  Projection/filter queries emit rows continuously as they are decoded. A whole-match aggregation (`GROUP BY` / `ORDER BY`) can only produce its final rows once the broadcast ends.  ### Rate Limits: | Type | Limit | | ---- | ----- | | IP | With broadcast_url: 20req/m<br>With match_id: 6req/h | | Key | With broadcast_url: -<br>With match_id: 20req/10m, 100req/h | | Global | With broadcast_url: 100req/m<br>With match_id: 100req/10m, 500req/h | 
         * @summary Live Demo Query (SSE)
         * @param {string} query SQL query to run over the broadcast\&#39;s entity/event tables (see &#x60;/demo/schema&#x60;).
         * @param {number | null} [matchId] Match to spectate and stream. Provide this or &#x60;broadcast_url&#x60;; &#x60;broadcast_url&#x60; wins if both are given. Resolving a match spectates its lobby and is rate-limited.
         * @param {string | null} [broadcastUrl] Explicit broadcast base URL (from &#x60;/live/urls&#x60;). Provide this or &#x60;match_id&#x60;.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        liveQuery: async (query: string, matchId?: number | null, broadcastUrl?: string | null, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'query' is not null or undefined
            assertParamExists('liveQuery', 'query', query)
            const localVarPath = `/v1/matches/demo/live/query`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (query !== undefined) {
                localVarQueryParameter['query'] = query;
            }

            if (matchId !== undefined) {
                localVarQueryParameter['match_id'] = matchId;
            }

            if (broadcastUrl !== undefined) {
                localVarQueryParameter['broadcast_url'] = broadcastUrl;
            }

            localVarHeaderParameter['Accept'] = 'text/event-stream';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *  Returns the queryable schema of a match\'s demo file: every entity and event table with its columns and Arrow types.  By default this returns the schema of the most recent match we have a demo for. Optionally pass `match_id` to read the schema for a specific match; if we don\'t already have its salts, they are fetched from Steam (rate limited, see `/{match_id}/salts`).     
         * @summary Demo Schema
         * @param {number | null} [matchId] Match to read the schema for. If omitted, the schema of the most recent match we have a demo for is returned. When set, the demo\&#39;s salts are fetched (rate limited) if they are not already stored.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        schema: async (matchId?: number | null, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/matches/demo/schema`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (matchId !== undefined) {
                localVarQueryParameter['match_id'] = matchId;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *  Returns the status of a demo query job. While `queued`/`running` it includes a rough `estimated_wait_seconds`; when `done` it includes `result_url` (a public link to the Parquet artifact, or the zstd-compressed `.ndjson.zst` artifact); when `failed` it includes `error`. 
         * @summary Demo Query Status
         * @param {string} jobId Job id returned by POST /demo/query
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        status: async (jobId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'jobId' is not null or undefined
            assertParamExists('status', 'jobId', jobId)
            const localVarPath = `/v1/matches/demo/query/{job_id}`
                .replace('{job_id}', encodeURIComponent(String(jobId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *  Submit a SQL query against a match\'s demo file. The work (download + decompress + parse + query) takes ~55s, so this is asynchronous: the endpoint returns a `job_id` you poll via `/demo/query/{job_id}`. Once done, the status response carries a public URL to the result artifact (Parquet or NDJSON).  Identical `(match_id, query, format)` submissions are deduplicated and reuse a cached result.  ### Rate Limits: | Type | Limit | | ---- | ----- | | IP | 20req/h | | Key | 200req/h | | Global | 400req/h | 
         * @summary Demo Query
         * @param {DemoQueryRequest} demoQueryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        submit: async (demoQueryRequest: DemoQueryRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'demoQueryRequest' is not null or undefined
            assertParamExists('submit', 'demoQueryRequest', demoQueryRequest)
            const localVarPath = `/v1/matches/demo/query`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(demoQueryRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DemoApi - functional programming interface
 */
export const DemoApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DemoApiAxiosParamCreator(configuration)
    return {
        /**
         *  Run a SQL query over a match\'s **live** broadcast and stream result rows over Server-Sent Events as the match plays, instead of waiting for the demo to finish (see the async `/demo/query`).  Provide either `match_id` (the server spectates the lobby to obtain the broadcast URL) or an explicit `broadcast_url` from `/live/urls`.  Projection/filter queries emit rows continuously as they are decoded. A whole-match aggregation (`GROUP BY` / `ORDER BY`) can only produce its final rows once the broadcast ends.  ### Rate Limits: | Type | Limit | | ---- | ----- | | IP | With broadcast_url: 20req/m<br>With match_id: 6req/h | | Key | With broadcast_url: -<br>With match_id: 20req/10m, 100req/h | | Global | With broadcast_url: 100req/m<br>With match_id: 100req/10m, 500req/h | 
         * @summary Live Demo Query (SSE)
         * @param {string} query SQL query to run over the broadcast\&#39;s entity/event tables (see &#x60;/demo/schema&#x60;).
         * @param {number | null} [matchId] Match to spectate and stream. Provide this or &#x60;broadcast_url&#x60;; &#x60;broadcast_url&#x60; wins if both are given. Resolving a match spectates its lobby and is rate-limited.
         * @param {string | null} [broadcastUrl] Explicit broadcast base URL (from &#x60;/live/urls&#x60;). Provide this or &#x60;match_id&#x60;.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async liveQuery(query: string, matchId?: number | null, broadcastUrl?: string | null, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.liveQuery(query, matchId, broadcastUrl, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DemoApi.liveQuery']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         *  Returns the queryable schema of a match\'s demo file: every entity and event table with its columns and Arrow types.  By default this returns the schema of the most recent match we have a demo for. Optionally pass `match_id` to read the schema for a specific match; if we don\'t already have its salts, they are fetched from Steam (rate limited, see `/{match_id}/salts`).     
         * @summary Demo Schema
         * @param {number | null} [matchId] Match to read the schema for. If omitted, the schema of the most recent match we have a demo for is returned. When set, the demo\&#39;s salts are fetched (rate limited) if they are not already stored.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async schema(matchId?: number | null, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DemoSchemaResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.schema(matchId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DemoApi.schema']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         *  Returns the status of a demo query job. While `queued`/`running` it includes a rough `estimated_wait_seconds`; when `done` it includes `result_url` (a public link to the Parquet artifact, or the zstd-compressed `.ndjson.zst` artifact); when `failed` it includes `error`. 
         * @summary Demo Query Status
         * @param {string} jobId Job id returned by POST /demo/query
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async status(jobId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DemoQueryStatusResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.status(jobId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DemoApi.status']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         *  Submit a SQL query against a match\'s demo file. The work (download + decompress + parse + query) takes ~55s, so this is asynchronous: the endpoint returns a `job_id` you poll via `/demo/query/{job_id}`. Once done, the status response carries a public URL to the result artifact (Parquet or NDJSON).  Identical `(match_id, query, format)` submissions are deduplicated and reuse a cached result.  ### Rate Limits: | Type | Limit | | ---- | ----- | | IP | 20req/h | | Key | 200req/h | | Global | 400req/h | 
         * @summary Demo Query
         * @param {DemoQueryRequest} demoQueryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async submit(demoQueryRequest: DemoQueryRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DemoQueryJobResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.submit(demoQueryRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DemoApi.submit']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DemoApi - factory interface
 */
export const DemoApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DemoApiFp(configuration)
    return {
        /**
         *  Run a SQL query over a match\'s **live** broadcast and stream result rows over Server-Sent Events as the match plays, instead of waiting for the demo to finish (see the async `/demo/query`).  Provide either `match_id` (the server spectates the lobby to obtain the broadcast URL) or an explicit `broadcast_url` from `/live/urls`.  Projection/filter queries emit rows continuously as they are decoded. A whole-match aggregation (`GROUP BY` / `ORDER BY`) can only produce its final rows once the broadcast ends.  ### Rate Limits: | Type | Limit | | ---- | ----- | | IP | With broadcast_url: 20req/m<br>With match_id: 6req/h | | Key | With broadcast_url: -<br>With match_id: 20req/10m, 100req/h | | Global | With broadcast_url: 100req/m<br>With match_id: 100req/10m, 500req/h | 
         * @summary Live Demo Query (SSE)
         * @param {DemoApiLiveQueryRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        liveQuery(requestParameters: DemoApiLiveQueryRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.liveQuery(requestParameters.query, requestParameters.matchId, requestParameters.broadcastUrl, options).then((request) => request(axios, basePath));
        },
        /**
         *  Returns the queryable schema of a match\'s demo file: every entity and event table with its columns and Arrow types.  By default this returns the schema of the most recent match we have a demo for. Optionally pass `match_id` to read the schema for a specific match; if we don\'t already have its salts, they are fetched from Steam (rate limited, see `/{match_id}/salts`).     
         * @summary Demo Schema
         * @param {DemoApiSchemaRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        schema(requestParameters: DemoApiSchemaRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<DemoSchemaResponse> {
            return localVarFp.schema(requestParameters.matchId, options).then((request) => request(axios, basePath));
        },
        /**
         *  Returns the status of a demo query job. While `queued`/`running` it includes a rough `estimated_wait_seconds`; when `done` it includes `result_url` (a public link to the Parquet artifact, or the zstd-compressed `.ndjson.zst` artifact); when `failed` it includes `error`. 
         * @summary Demo Query Status
         * @param {DemoApiStatusRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        status(requestParameters: DemoApiStatusRequest, options?: RawAxiosRequestConfig): AxiosPromise<DemoQueryStatusResponse> {
            return localVarFp.status(requestParameters.jobId, options).then((request) => request(axios, basePath));
        },
        /**
         *  Submit a SQL query against a match\'s demo file. The work (download + decompress + parse + query) takes ~55s, so this is asynchronous: the endpoint returns a `job_id` you poll via `/demo/query/{job_id}`. Once done, the status response carries a public URL to the result artifact (Parquet or NDJSON).  Identical `(match_id, query, format)` submissions are deduplicated and reuse a cached result.  ### Rate Limits: | Type | Limit | | ---- | ----- | | IP | 20req/h | | Key | 200req/h | | Global | 400req/h | 
         * @summary Demo Query
         * @param {DemoApiSubmitRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        submit(requestParameters: DemoApiSubmitRequest, options?: RawAxiosRequestConfig): AxiosPromise<DemoQueryJobResponse> {
            return localVarFp.submit(requestParameters.demoQueryRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for liveQuery operation in DemoApi.
 */
export interface DemoApiLiveQueryRequest {
    /**
     * SQL query to run over the broadcast\&#39;s entity/event tables (see &#x60;/demo/schema&#x60;).
     */
    readonly query: string

    /**
     * Match to spectate and stream. Provide this or &#x60;broadcast_url&#x60;; &#x60;broadcast_url&#x60; wins if both are given. Resolving a match spectates its lobby and is rate-limited.
     */
    readonly matchId?: number | null

    /**
     * Explicit broadcast base URL (from &#x60;/live/urls&#x60;). Provide this or &#x60;match_id&#x60;.
     */
    readonly broadcastUrl?: string | null
}

/**
 * Request parameters for schema operation in DemoApi.
 */
export interface DemoApiSchemaRequest {
    /**
     * Match to read the schema for. If omitted, the schema of the most recent match we have a demo for is returned. When set, the demo\&#39;s salts are fetched (rate limited) if they are not already stored.
     */
    readonly matchId?: number | null
}

/**
 * Request parameters for status operation in DemoApi.
 */
export interface DemoApiStatusRequest {
    /**
     * Job id returned by POST /demo/query
     */
    readonly jobId: string
}

/**
 * Request parameters for submit operation in DemoApi.
 */
export interface DemoApiSubmitRequest {
    readonly demoQueryRequest: DemoQueryRequest
}

/**
 * DemoApi - object-oriented interface
 */
export class DemoApi extends BaseAPI {
    /**
     *  Run a SQL query over a match\'s **live** broadcast and stream result rows over Server-Sent Events as the match plays, instead of waiting for the demo to finish (see the async `/demo/query`).  Provide either `match_id` (the server spectates the lobby to obtain the broadcast URL) or an explicit `broadcast_url` from `/live/urls`.  Projection/filter queries emit rows continuously as they are decoded. A whole-match aggregation (`GROUP BY` / `ORDER BY`) can only produce its final rows once the broadcast ends.  ### Rate Limits: | Type | Limit | | ---- | ----- | | IP | With broadcast_url: 20req/m<br>With match_id: 6req/h | | Key | With broadcast_url: -<br>With match_id: 20req/10m, 100req/h | | Global | With broadcast_url: 100req/m<br>With match_id: 100req/10m, 500req/h | 
     * @summary Live Demo Query (SSE)
     * @param {DemoApiLiveQueryRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public liveQuery(requestParameters: DemoApiLiveQueryRequest, options?: RawAxiosRequestConfig) {
        return DemoApiFp(this.configuration).liveQuery(requestParameters.query, requestParameters.matchId, requestParameters.broadcastUrl, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *  Returns the queryable schema of a match\'s demo file: every entity and event table with its columns and Arrow types.  By default this returns the schema of the most recent match we have a demo for. Optionally pass `match_id` to read the schema for a specific match; if we don\'t already have its salts, they are fetched from Steam (rate limited, see `/{match_id}/salts`).     
     * @summary Demo Schema
     * @param {DemoApiSchemaRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public schema(requestParameters: DemoApiSchemaRequest = {}, options?: RawAxiosRequestConfig) {
        return DemoApiFp(this.configuration).schema(requestParameters.matchId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *  Returns the status of a demo query job. While `queued`/`running` it includes a rough `estimated_wait_seconds`; when `done` it includes `result_url` (a public link to the Parquet artifact, or the zstd-compressed `.ndjson.zst` artifact); when `failed` it includes `error`. 
     * @summary Demo Query Status
     * @param {DemoApiStatusRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public status(requestParameters: DemoApiStatusRequest, options?: RawAxiosRequestConfig) {
        return DemoApiFp(this.configuration).status(requestParameters.jobId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *  Submit a SQL query against a match\'s demo file. The work (download + decompress + parse + query) takes ~55s, so this is asynchronous: the endpoint returns a `job_id` you poll via `/demo/query/{job_id}`. Once done, the status response carries a public URL to the result artifact (Parquet or NDJSON).  Identical `(match_id, query, format)` submissions are deduplicated and reuse a cached result.  ### Rate Limits: | Type | Limit | | ---- | ----- | | IP | 20req/h | | Key | 200req/h | | Global | 400req/h | 
     * @summary Demo Query
     * @param {DemoApiSubmitRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public submit(requestParameters: DemoApiSubmitRequest, options?: RawAxiosRequestConfig) {
        return DemoApiFp(this.configuration).submit(requestParameters.demoQueryRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

