# coding: utf-8

"""
    Deadlock API

     ## API Clients  We have auto generated and updated clients for many languages. You can find them here: [https://github.com/deadlock-api/openapi-clients](https://github.com/deadlock-api/openapi-clients)  ## Support the Deadlock API  Whether you're building your own database, developing data science projects, or enhancing your website with game and player analytics, the Deadlock API has the data you need.  Your sponsorship helps keep this resource open, free and future-proof for everyone. By supporting the Deadlock API, you will enable continued development, new features and reliable access for developers, analysts and streamers worldwide.  Help us continue to provide the data you need - sponsor the Deadlock API today!  **-> You can Sponsor the Deadlock API on [Patreon](https://www.patreon.com/c/user?u=68961896) or [GitHub](https://github.com/sponsors/raimannma)**  ## Disclaimer _deadlock-api.com is not endorsed by Valve and does not reflect the views or opinions of Valve or anyone officially involved in producing or managing Valve properties. Valve and all associated properties are trademarks or registered trademarks of Valve Corporation_         

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from deadlock_api_client.models.player_card_slot import PlayerCardSlot
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PlayerCard(BaseModel):
    """
    PlayerCard
    """ # noqa: E501
    account_id: Annotated[int, Field(strict=True, ge=0)]
    ranked_badge_level: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="See more: <https://api.deadlock-api.com/v1/assets/ranks>")
    ranked_rank: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="See more: <https://api.deadlock-api.com/v1/assets/ranks>")
    ranked_subrank: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="See more: <https://api.deadlock-api.com/v1/assets/ranks>")
    slots: List[PlayerCardSlot]
    __properties: ClassVar[List[str]] = ["account_id", "ranked_badge_level", "ranked_rank", "ranked_subrank", "slots"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PlayerCard from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in slots (list)
        _items = []
        if self.slots:
            for _item_slots in self.slots:
                _items.append(_item_slots.to_dict() if _item_slots is not None else None)
            _dict['slots'] = _items
        # set to None if ranked_badge_level (nullable) is None
        # and model_fields_set contains the field
        if self.ranked_badge_level is None and "ranked_badge_level" in self.model_fields_set:
            _dict['ranked_badge_level'] = None

        # set to None if ranked_rank (nullable) is None
        # and model_fields_set contains the field
        if self.ranked_rank is None and "ranked_rank" in self.model_fields_set:
            _dict['ranked_rank'] = None

        # set to None if ranked_subrank (nullable) is None
        # and model_fields_set contains the field
        if self.ranked_subrank is None and "ranked_subrank" in self.model_fields_set:
            _dict['ranked_subrank'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PlayerCard from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "account_id": obj.get("account_id"),
            "ranked_badge_level": obj.get("ranked_badge_level"),
            "ranked_rank": obj.get("ranked_rank"),
            "ranked_subrank": obj.get("ranked_subrank"),
            "slots": [PlayerCardSlot.from_dict(_item) for _item in obj["slots"]] if obj.get("slots") is not None else None
        })
        return _obj


