# coding: utf-8

"""
    Deadlock API

     ## API Clients  We have auto generated and updated clients for many languages. You can find them here: [https://github.com/deadlock-api/openapi-clients](https://github.com/deadlock-api/openapi-clients)  ## Support the Deadlock API  Whether you're building your own database, developing data science projects, or enhancing your website with game and player analytics, the Deadlock API has the data you need.  Your sponsorship helps keep this resource open, free and future-proof for everyone. By supporting the Deadlock API, you will enable continued development, new features and reliable access for developers, analysts and streamers worldwide.  Help us continue to provide the data you need - sponsor the Deadlock API today!  **-> You can Sponsor the Deadlock API on [Patreon](https://www.patreon.com/c/user?u=68961896) or [GitHub](https://github.com/sponsors/raimannma)**  ## Disclaimer _deadlock-api.com is not endorsed by Valve and does not reflect the views or opinions of Valve or anyone officially involved in producing or managing Valve properties. Valve and all associated properties are trademarks or registered trademarks of Valve Corporation_         

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Union
from deadlock_api_client.models.draft_buckets import DraftBuckets
from deadlock_api_client.models.item_draft_round_per_game_round import ItemDraftRoundPerGameRound
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class StreetBrawl(BaseModel):
    """
    StreetBrawl
    """ # noqa: E501
    apper_round: List[StrictInt]
    buy_time: List[StrictInt]
    buy_time_grace_period: Union[StrictFloat, StrictInt]
    comeback_bonus_health: StrictInt
    comeback_bonus_health_critical: StrictInt
    gold_per_round: List[StrictInt]
    item_draft_rerolls_per_round: List[StrictInt]
    item_draft_rounds_per_game_round: List[ItemDraftRoundPerGameRound]
    item_drafts: Dict[str, DraftBuckets]
    lane_number: StrictInt
    objective_max_health: List[StrictInt]
    overtime_respawn_time_increase: List[Union[StrictFloat, StrictInt]]
    overtime_respawn_time_increase_urgent: List[Union[StrictFloat, StrictInt]]
    overtime_trooper_damage_scale: List[Union[StrictFloat, StrictInt]]
    overtime_trooper_health_scale: List[Union[StrictFloat, StrictInt]]
    pre_buy_time: List[Union[StrictFloat, StrictInt]]
    respawn_times: List[StrictInt]
    round_length_minutes: List[StrictInt]
    round_length_minutes_urgent: List[Union[StrictFloat, StrictInt]]
    score_to_win: StrictInt
    scoring_time: Union[StrictFloat, StrictInt]
    tier1_max_resist_time: Union[StrictFloat, StrictInt]
    tier2_bonus_health: StrictInt
    tier2_max_resist_time: Union[StrictFloat, StrictInt]
    trooper_spawn_before_round_start_timer: Union[StrictFloat, StrictInt]
    trooper_spawn_timer: List[Union[StrictFloat, StrictInt]]
    ultimate_unlock_round: StrictInt
    zip_boost_cooldown_on_start: Union[StrictFloat, StrictInt]
    __properties: ClassVar[List[str]] = ["apper_round", "buy_time", "buy_time_grace_period", "comeback_bonus_health", "comeback_bonus_health_critical", "gold_per_round", "item_draft_rerolls_per_round", "item_draft_rounds_per_game_round", "item_drafts", "lane_number", "objective_max_health", "overtime_respawn_time_increase", "overtime_respawn_time_increase_urgent", "overtime_trooper_damage_scale", "overtime_trooper_health_scale", "pre_buy_time", "respawn_times", "round_length_minutes", "round_length_minutes_urgent", "score_to_win", "scoring_time", "tier1_max_resist_time", "tier2_bonus_health", "tier2_max_resist_time", "trooper_spawn_before_round_start_timer", "trooper_spawn_timer", "ultimate_unlock_round", "zip_boost_cooldown_on_start"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of StreetBrawl from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in item_draft_rounds_per_game_round (list)
        _items = []
        if self.item_draft_rounds_per_game_round:
            for _item_item_draft_rounds_per_game_round in self.item_draft_rounds_per_game_round:
                _items.append(_item_item_draft_rounds_per_game_round.to_dict() if _item_item_draft_rounds_per_game_round is not None else None)
            _dict['item_draft_rounds_per_game_round'] = _items
        # override the default output from pydantic by calling `to_dict()` of each value in item_drafts (dict)
        _field_dict = {}
        if self.item_drafts:
            for _key_item_drafts in self.item_drafts:
                _field_dict[_key_item_drafts] = self.item_drafts[_key_item_drafts].to_dict() if self.item_drafts[_key_item_drafts] is not None else None
            _dict['item_drafts'] = _field_dict
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of StreetBrawl from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "apper_round": obj.get("apper_round"),
            "buy_time": obj.get("buy_time"),
            "buy_time_grace_period": obj.get("buy_time_grace_period"),
            "comeback_bonus_health": obj.get("comeback_bonus_health"),
            "comeback_bonus_health_critical": obj.get("comeback_bonus_health_critical"),
            "gold_per_round": obj.get("gold_per_round"),
            "item_draft_rerolls_per_round": obj.get("item_draft_rerolls_per_round"),
            "item_draft_rounds_per_game_round": [ItemDraftRoundPerGameRound.from_dict(_item) for _item in obj["item_draft_rounds_per_game_round"]] if obj.get("item_draft_rounds_per_game_round") is not None else None,
            "item_drafts": dict(
                (_k, DraftBuckets.from_dict(_v))
                for _k, _v in obj["item_drafts"].items()
            )
            if obj.get("item_drafts") is not None
            else None,
            "lane_number": obj.get("lane_number"),
            "objective_max_health": obj.get("objective_max_health"),
            "overtime_respawn_time_increase": obj.get("overtime_respawn_time_increase"),
            "overtime_respawn_time_increase_urgent": obj.get("overtime_respawn_time_increase_urgent"),
            "overtime_trooper_damage_scale": obj.get("overtime_trooper_damage_scale"),
            "overtime_trooper_health_scale": obj.get("overtime_trooper_health_scale"),
            "pre_buy_time": obj.get("pre_buy_time"),
            "respawn_times": obj.get("respawn_times"),
            "round_length_minutes": obj.get("round_length_minutes"),
            "round_length_minutes_urgent": obj.get("round_length_minutes_urgent"),
            "score_to_win": obj.get("score_to_win"),
            "scoring_time": obj.get("scoring_time"),
            "tier1_max_resist_time": obj.get("tier1_max_resist_time"),
            "tier2_bonus_health": obj.get("tier2_bonus_health"),
            "tier2_max_resist_time": obj.get("tier2_max_resist_time"),
            "trooper_spawn_before_round_start_timer": obj.get("trooper_spawn_before_round_start_timer"),
            "trooper_spawn_timer": obj.get("trooper_spawn_timer"),
            "ultimate_unlock_round": obj.get("ultimate_unlock_round"),
            "zip_boost_cooldown_on_start": obj.get("zip_boost_cooldown_on_start")
        })
        return _obj


