/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package deadlock_api_client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import deadlock_api_client.models.RankResponse
import deadlock_api_client.models.LastRankedMatch

class RankResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RankResponse
        //val modelInstance = RankResponse()

        // to test the property `badge` - Rank badge, `tier * 10 + subrank`, including the progress the last ranked match awarded. Eternus subranks are percentile-based and refreshed daily by Valve, so within Eternus this is the badge the player entered their latest ranked match with. `0` when no recent ranked match reports a rank. See more: <https://api.deadlock-api.com/v1/assets/ranks>
        should("test badge") {
            // uncomment below to test the property
            //modelInstance.badge shouldBe ("TODO")
        }

        // to test the property `rank` - Rank tier, `0` when unknown.
        should("test rank") {
            // uncomment below to test the property
            //modelInstance.rank shouldBe ("TODO")
        }

        // to test the property `subrank` - Sub-rank within the tier, `0` when unknown.
        should("test subrank") {
            // uncomment below to test the property
            //modelInstance.subrank shouldBe ("TODO")
        }

        // to test the property `lastMatch` - Rank metadata of the ranked match the badge was read from. `null` when none of the player's recent ranked matches reports a rank.
        should("test lastMatch") {
            // uncomment below to test the property
            //modelInstance.lastMatch shouldBe ("TODO")
        }

    }
}
